### ISSUE TITLE
[FR] Headers should have collapse option by default

### ISSUE THREAD

**Issue by lynrayy** [AppFlowy-IO/AppFlowy#6333] opened 2024-09-17 17:23 UTC
### Description

Since the heading implies a short description of the following block of text, it would be convenient to be able to collapse the entire contents of the heading with one click. This is already implemented in Notion and even MS Word by default.

It would also be nice if when creating headers there was some indentation depending on how much they are nested inside each other

### Impact

Structuring and formatting will become more efficient when writing by time, and it will be easier to use and find the necessary part of the information. 

**This will also allow you to match the functionality of Notion.**

### Additional Context

This is how it looks like in Notion:
![image](https://github.com/user-attachments/assets/b673232e-5f71-4b0c-815f-fea411f919ea)

In MS Word:
![image](https://github.com/user-attachments/assets/8e9d6943-07be-4bc8-b65a-ad4821964d51)

**Comment by annieappflowy** [comment] 2024-10-03 02:45
#3035

**Comment by Ahad-patel** [comment] 2024-11-11 10:59
hey @annieappflowy should close this one too, cos its duplicate of #3035

**Closed** 2024-11-11 12:07 UTC
Labels: new feature, editor, 2024, Q4 24
