### ISSUE TITLE
[Bug] unable to type email_verified_at

### ISSUE THREAD

**Issue by Joso997** [AppFlowy-IO/AppFlowy#3624] opened 2023-10-05 12:23 UTC
### Bug Description

I am unable to write email_verified_at in a table. Copy Paste works though

### How to Reproduce

Just start typing email_verified_at 

### Expected Behavior

it should be email_verified_at instead of email _verified_ at

I can't reproduce it here in text, anyway like above where verified is italic without spaces between words.
I see this might be a problem here on GitHub too.

### Operating System

Windows 10

### AppFlowy Version(s)

0.3.4

**Comment by MayurSMahajan** [comment] 2023-10-05 15:25
Hey @Joso997! So you are not able to type things with _ (underscore) around them.
This is because wrapping words with an underscore is a markdown we use and also GitHub uses.
One way to get around it is by using a backslash like this: 
`\_sometext\_` this will show up like \_sometext\_ in Github

But now I have noticed that AppFlowy is not supporting the backslash key (\). So that is a bug.
Thanks for bringing this to our attention.

**Comment by DevaanshPathak** [comment] 2023-10-06 16:42
@MayurSMahajan I would like to work on this issue, please assign it to me. Thanks!

**Comment by MayurSMahajan** [comment] 2023-10-07 05:04
@DevaanshPathak  To solve this issue, you actually want to solve #3628. Have a crack at it.

**Comment by MayurSMahajan** [comment] 2023-10-07 05:05
Oops I have already assigned #3628 to someone else, please look for other issues!

**Comment by DevaanshPathak** [comment] 2023-10-07 05:06
Sure, Thanks @MayurSMahajan

**Comment by Xazin** [comment] 2023-10-25 18:53
Duplicate of #3628

**Closed by Xazin** 2023-10-25 18:53 UTC
