### ISSUE TITLE
[Bug] Emojis as Unicode on Windows

### ISSUE THREAD

**Issue by voizuu** [AppFlowy-IO/appflowy#45] opened 2021-11-20 04:44 UTC
**Describe the bug**
Emojis are showing up as their Unicode equivalent.

**To Reproduce**
1. Download the 0.0.2 zip
2. Extract all
3. Run the app_flowy.exe
4. Emojis display as Unicode

**Expected behavior**
I expected the emojis to display as would normal.

**Screenshots**
![d4ac99baf18760008ceb924753f54937-png](https://user-images.githubusercontent.com/49259224/142714619-60defdb4-6087-4f25-8c10-715aac2602a0.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Microsoft Edge
 - Version: 0.0.2

**Comment by Pranav4399** [comment] 2021-11-21 09:24
Is this fixed already ? I'm not able to reproduce this issue when I tried ?

**Comment by annieappflowy** [comment] 2021-11-22 05:33
Unable to reproduce. Potentially bring about patent infringement if solving this inconsistency issue. Low-priority. Closing it.

**Closed** 2021-11-22 05:33 UTC
Labels: notes
