### ISSUE TITLE
[FR] Create a new theme for AppFlowy Editor

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#1070] opened 2022-09-16 12:21 UTC
Add a new theme to the theme library.

Reference: https://github.com/AppFlowy-IO/AppFlowy/blob/main/frontend/app_flowy/packages/appflowy_editor/documentation/customizing.md#customizing-a-theme-new-feature-in-005-alpha

**Comment by ChiragKr04** [comment] 2022-09-29 13:13
@annieappflowy Can I work on this? And do we need to add only the theme is given in reference?

**Comment by annieappflowy** [comment] 2022-09-30 10:32
@ChiragKr04 , I assigned this issue to you. Can you elaborate on your question?

**Comment by MayurSMahajan** [comment] 2022-10-03 18:18
I know the issue is already assigned but I had a small doubt. You want new default themes, This will enable users to directly select from a range of newly created custom themes. 

So basically what I am trying to say is that the person solving this issue will submit a set of new themes that the user doesn't need to customize himself. The user can just simply should be able to write `editorStyle: EditorStyle.monokai()`, here monokai being one of the themes that the person writing a PR will create?

Is that correct? And if yes then can I work on this issue simultaneously with the person who is assigned. 
I am experienced in UI/UX development and Flutter development and I feel confident about contributing on this issue.

**Comment by annieappflowy** [comment] 2022-10-04 14:31
@MayurSMahajan , yes, we’d like to offer users with a diverse set of themes. Multiple people can work on this issue together. You can just create a separate issue for the theme you’d like to create. I’ll then label it accordingly. If you need help with this task, please feel free to reach out to @LucasXu0 on Discord.

**Comment by annieappflowy** [comment] 2022-10-04 14:31
@ChiragKr04 , can you create a separate issue for the theme you’re building? I’ll then label it accordingly!. Thanks

**Comment by ChiragKr04** [comment] 2022-10-04 14:33
> @ChiragKr04 , can you create a separate issue for the theme you’re building? I’ll then label it accordingly!. Thanks

Sure
Should I pick on my own or you got any suggestions? 😃

**Comment by ChiragKr04** [comment] 2022-10-04 14:39
@MayurSMahajan You can pick any theme and If you pick one please let me know. 😄

**Comment by MayurSMahajan** [comment] 2022-10-05 16:12
Okay so I will think of themes and design them in Figma first. I'll tell their names to you so you can create issues. And soon I will submit PR with the code containing the Themes

**Comment by MayurSMahajan** [comment] 2022-10-05 16:17
> @ChiragKr04 , can you create a separate issue for the theme you’re building? I’ll then label it accordingly!. Thanks

@ChiragKr04 I think @annieappflowy meant that you have to create a different issue and submit your work there, since previously this issue was assigned to you.

**Comment by MayurSMahajan** [comment] 2022-10-05 16:18
> @MayurSMahajan You can pick any theme and If you pick one please let me know. smile

I'll try to suggest you some themes that you can work on parallel

**Comment by annieappflowy** [comment] 2022-10-10 04:11
@MayurSMahajan @ChiragKr04  have you guys figured out what themes you'd like to work on?

**Comment by MayurSMahajan** [comment] 2022-10-10 06:02
Yes, I have a few in mind, I am going to create one theme with all the colors in the AppFlowy logo, and then one theme with each of the colors individually together with their lighter and darker palettes. Actually I am having some trouble setting up AppFlowy, I have an old laptop, in a few days I am getting a new one, so then I will be able to work on the issue.

Once I can complete the setup I will send some Figma prototypes to @ChiragKr04 and then he can work on those. By the way @ChiragKr04 you are free to create your own designs in the meantime if you want.

**Comment by ChiragKr04** [comment] 2022-10-10 06:27
> @MayurSMahajan @ChiragKr04 have you guys figured out what themes you'd like to work on?

I think I'll do the Monokai theme or Abyss theme palettes. 

Monokai Theme
![image](https://user-images.githubusercontent.com/62651867/194808634-dcc021c9-d31d-41da-bbb7-cb8657d96096.png)


Abyss Theme
![image](https://user-images.githubusercontent.com/62651867/194808502-d4e7f72d-5df5-4651-a36f-1e6151c1bd63.png)

Please check if its okay @annieappflowy .

**Comment by annieappflowy** [comment] 2022-10-10 06:38
Looks great! 
BTW, this will be extended to a theme store in the future. Hope your themes are people's favorites!

**Comment by ChiragKr04** [comment] 2022-10-10 06:42
> Looks great! BTW, this will be extended to a theme store in the future. Hope your themes are people's favorites!

Amazing! Yes, both are the top ones.

**Comment by MayurSMahajan** [comment] 2022-10-13 17:29
Hey! This is my current progress so far. Give me honest feedback.

This is an all color light theme, using all the colors in the AppFlowy logo, except the blue one.

![Screenshot from 2022-10-13 22-51-19](https://user-images.githubusercontent.com/47064215/195664427-5c4e051f-d336-4423-991a-1a4cda846af5.png)

Checkout the figma design here:
PS: To edit the design, simply copy the frame and paste it in your figma design file.

https://www.figma.com/file/M4Ysq0QQ7zdUsStSajckto/AppFlowy_Base?node-id=0%3A1

This is a dark purple theme, using the purple in the AppFlowy logo, it contrasts well with the Pink in the logo, so I have kept that too.

![Screenshot from 2022-10-13 22-52-16](https://user-images.githubusercontent.com/47064215/195665251-e3dfba5b-7ed2-46b8-928b-511cd4a0965a.png)

Checkout the figma design here:
PS: To edit the design, simply copy the frame and paste it in your figma design file.

Please give me honest feedback.

**Comment by MayurSMahajan** [comment] 2022-10-13 17:46
Here is one more

3) This one just uses the logo pink with a light theme.

![Screenshot from 2022-10-13 23-14-24](https://user-images.githubusercontent.com/47064215/195668539-e6e46794-cb0c-49a8-9dc8-818bdd442672.png)

**Comment by annieappflowy** [comment] 2022-10-14 03:30
Wow, looks amazing!!! @MayurSMahajan , I love the yellow theme. It's very cute!

**Comment by ChiragKr04** [comment] 2022-10-14 03:53
Looks amazing man 🚀

**Comment by MayurSMahajan** [comment] 2022-10-14 15:24
Thank you guys! I am getting a new laptop in a few days until then I won't be able to code these designs in the flutter app. So I am working on more designs. Until then If @ChiragKr04 wants to implement any one of the above designs then definitely go for it!

**Comment by MayurSMahajan** [comment] 2022-11-12 14:33
I have setted up the application on my pc. I am going through the codebase, since I am a beginner its a bit complex, but I will keep working on it. Will keep you guys in touch.

**Comment by Heccubernny** [comment] 2023-03-12 06:43
@annieappflowy good day, has this issue been resolved?. And also I think the referenced linked has been changed. It is resulting to page not found. Although I was later been able to navigate to it using this link: https://github.com/AppFlowy-IO/AppFlowy/blob/main/frontend/appflowy_flutter/packages/appflowy_editor/documentation/customizing.md

**Comment by MayurSMahajan** [comment] 2023-03-26 18:30
@Heccubernny Sorry for replying late, you can definitely create a new theme and contribute to AppFlowy. In that case, you will have to create an issue for your theme, and then implement a light and a dark version for it. Thank you!

**Closed** 2023-07-11 12:59 UTC
Labels: help wanted, good first issue for devs, editor, hacktoberfest
