### ISSUE TITLE
[Bug] Input does support Chinese Input (including Sougou Pinyin and Mac embedded Chinese input)

### ISSUE THREAD

**Issue by tantanorange** [AppFlowy-IO/AppFlowy#770] opened 2022-08-05 07:23 UTC
**Describe the bug**
AppFlowy version 0.0.4(1) does not support Chinese input.

**To Reproduce**
1. Create a new page
2. Shift input source from English to Chinese Pinyin (Mac embedded Chinese input)
3. Start tying Chinese (the input frame won't follow the cursor), then type space to insert the characters. 
4. It shows the Chinese characters just fine. Now, try to delete the character. Typing "backspace" to delete does not work. And the arrow keys seem to malfunction as well (arrow keys will not move the cursor between texts but keep jumping around between app buttons)

**Expected behavior**
Using a Chinese input source to type Chinese should have the input frame following the cursor, meanwhile pushing "backspace" to delete should function, as well as others like the arrow keys.

**Screenshots**
0.0.4(1) 
<img width="278" alt="image" src="https://user-images.githubusercontent.com/44329336/183023037-8c1375ae-caa8-470c-ad8d-cd1d0fb674d8.png">

1. input frame does not follow the cursor:
<img width="1296" alt="image" src="https://user-images.githubusercontent.com/44329336/183023505-e31c76a3-420c-4cb9-9ba6-b21541e6f8c3.png">

2. cannot delete Chinese characters once input into the doc, and the delete key and arrows keys seem to malfunction as well.
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/44329336/183024260-c5e01ada-5208-4fe0-911e-5a5d48d750ef.png">

**Desktop (please complete the following information):**
 - OS: 12.4
 - Application 0.0.4(1)

**Comment by appflowy** [comment] 2022-08-08 03:46
Hi @tantanorange , this is a duplicate of https://github.com/AppFlowy-IO/AppFlowy/issues/735
Please keep an eye out for that issue ticket. Thanks for reporting the bug.

**Closed by appflowy** 2022-08-08 03:46 UTC

**Comment by tantanorange** [comment] 2022-08-10 03:09
@appflowy Thanks, will do! It's an amazing OSS, keep it up man!

**Comment by appflowy** [comment] 2022-08-10 03:22
> 

FYI, we're building a new editor that will fixes this problem.

**Comment by tantanorange** [comment] 2022-08-10 03:29
Sounds Awesome;)
