### ISSUE TITLE
[Bug] Fonts doesn't load or text is garbled

### ISSUE THREAD

**Issue by cmrajan** [AppFlowy-IO/AppFlowy#11] opened 2021-11-16 06:59 UTC
**Describe the bug**

**To Reproduce**
1. Install version 0.0.2 from the releases
2. Open the App
3. Garbled text
4. See Screenshot

**Expected behavior**
Show correct sample text

**Screenshots**
<img width="782" alt="image" src="https://user-images.githubusercontent.com/410065/141936407-788d0bc8-7497-49d7-8af0-bf3241a71dc4.png">

**Desktop (please complete the following information):**
 - OS: MacOS Sierra
 - Browser NA
 - Version 10.12.6

**Comment by annieappflowy** [comment] 2021-11-16 07:08
Hi cmrajan,

Thanks for checking us out! Could you please let us know your system's language?

Annie

**Comment by cmrajan** [comment] 2021-11-17 03:57
US-en

**Comment by appflowy** [comment] 2022-01-05 15:07
> Has this ever been reproduced by anyone? @cmrajan Do you still have this problem?

Annie was able to reproduce on her old MacBook

**Comment by apomalyn** [comment] 2022-07-19 13:46
I cannot reproduce the bug with MacOS Monterey and AppFlowy v0.0.4.1. Is anyone able to reproduce it now?

**Comment by MikeWallaceDev** [comment] 2022-07-28 14:17
Closing as nobody seems to reproduce this anymore

**Closed by MikeWallaceDev** 2022-07-28 14:17 UTC
Labels: bug
