### ISSUE TITLE
[FR] Web App interface for hosting

### ISSUE THREAD

**Issue by iamaravindim** [AppFlowy-IO/appflowy#177] opened 2021-12-17 18:04 UTC
**Use cases of the proposed feature**
Is it possible for a web interface to be made available for AppFlowy so that we can host it completely on a server as a Webapp and access it through the browser?

**what types of users can benefit from using your proposed feature**
This would help people to work on thing online as a team.

**Comment by nguillaumin** [comment] 2021-12-22 18:17
Duplicate of #89 ?

**Comment by MikeWallaceDev** [comment] 2021-12-23 02:32
Duplicate of #89

**Closed by MikeWallaceDev** 2021-12-23 02:32 UTC
Labels: enhancement
