### ISSUE TITLE
[FR] Zoom level settings

### ISSUE THREAD

**Issue by TieWay59** [AppFlowy-IO/AppFlowy#128] opened 2021-12-07 12:30 UTC
**1~3 main use cases of the proposed feature**
Just as in windows browsers, people press `ctrl +` and `ctrl -` to adjust the scale of the whole layout of the view. 
Many text editors have this feature, such as vs code.

**what types of users can benefit from using your proposed feature**
This can help when working on a different kind of screen device.
It's like a piece of `a11y` thing. Personally, I prefer everything a bit larger than current defaults.

**Additional context**
Looking forward to a stronger list of shortcut keys.

**Comment by annieappflowy** [comment] 2021-12-08 06:24
If we offer you a few font size choices, would that meet your needs?

**Comment by TieWay59** [comment] 2021-12-09 09:10
@annieappflowy sure, more choices will help a lot !

**Comment by v3ss0n** [comment] 2022-08-25 13:32
Unable to use on 4k and high DPI , cannot even zoom.

**Comment by zoli** [comment] 2023-01-19 19:21
How is this different from #1638?

**Comment by annieappflowy** [comment] 2023-01-20 00:45
@zoli , #1638 is a duplicate of this issue.

**Comment by Twilightssuperb** [comment] 2023-06-09 13:44
How about to increasing the priority of this issue?

**Closed** 2024-05-10 02:09 UTC
Labels: bug, new feature, 2024
