### ISSUE TITLE
[Bug] When enable Caps Lock it can not paste with Ctrl-V

### ISSUE THREAD

**Issue by chenyinheng30** [AppFlowy-IO/AppFlowy#839] opened 2022-08-12 10:47 UTC
**Describe the bug**
 In text pages, when the Caps Lock is enabled, pressing the Ctrl-V key has no effect,it can not paste.

**To Reproduce**
1. Open a text page.
2. Press Caps Lock.
3. Copy a text
4. Paste with Ctrl-V

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: Debian 11 bullseye 
 - Version v0.0.4

**Comment by ChiragKr04** [comment] 2022-08-13 15:09
I'm not able to reproduce this issue on `Windows 11`.

**Comment by annieappflowy** [comment] 2022-08-15 11:29
Hi @chenyinheng30 thanks for reporting the issue. This is a duplicate of https://github.com/AppFlowy-IO/AppFlowy/issues/530

I'm closing this one. You can keep an eye out there for the update.

**Closed by annieappflowy** 2022-08-15 11:29 UTC
