### ISSUE TITLE
[Bug]: Highlighted words are unreadable on Dark Mode (Windows 11)

### ISSUE THREAD

**Issue by faculemac** [AppFlowy-IO/AppFlowy#1163] opened 2022-09-26 03:28 UTC
### Bug Description

Contrast between the highlight background color and letter color is too low in dark mode (highlight background is too bright for white letters). It seems that the colors are the same in light and dark mode, which are fine for light mode but way too bright for dark mode.

### How to Reproduce

Open the app on Windows / macOS, choose dark mode and highlight a word.

### Expected Behavior

More contrast to make highlighted words readable.

### Operating System

Windows 11 21H2 Build 22000.978 / macOS Monterrey 12.6

### AppFlowy Version(s)

0.0.5.2

### Screenshots

![image](https://user-images.githubusercontent.com/69240976/192187180-78ba2ea2-7ead-41e9-b8b3-0ae97135b4d2.png)

**Comment by microBob** [comment] 2022-09-26 04:45
I can confirm this. It also looks like this in macOS as well.

**Comment by annieappflowy** [comment] 2022-09-27 13:02
Thanks for reporting this issue. This is a duplicate of https://github.com/AppFlowy-IO/AppFlowy/issues/336
You can keep an eye out for that issue.

**Closed by annieappflowy** 2022-09-27 13:02 UTC
