### ISSUE TITLE
[FR] Create a new page inside page

### ISSUE THREAD

**Issue by xky0007** [AppFlowy-IO/AppFlowy#5134] opened 2024-04-15 02:53 UTC
### Description

When type `/page`, create a new page inside current page and automatically open and edit the new page.

### Impact

Easy to add new linked doc to current page.

**Comment by Dav-sa** [comment] 2024-07-03 12:45
any updates ?

**Comment by DimaZava** [comment] 2024-08-29 15:51
Would like to make the same request. Simple, but very useful feature

**Comment by henri9813** [comment] 2024-10-26 19:18
Hello,

It's a duplicate of #5417 

Can you maybe close your issue please ?

Best regards,

**Closed** 2024-11-22 13:31 UTC
Labels: new feature, editor, organization, 2024, Q4 24
