### ISSUE TITLE
[FR] A Way to Disable Markdown parsing in AppFlowy

### ISSUE THREAD

**Issue by MayurSMahajan** [AppFlowy-IO/AppFlowy#3816] opened 2023-10-27 16:49 UTC
## Description

Can markdown parsing be something disabled via config setting? So if off and we want markdown, typing `/` to bring up the menu to choose a "markdown" option (like code block, image, table, etc. already are today) would switch that block to markdown?

I like the shortcut to avoid having markdown parsed, but I would prefer to disable markdown completely by default and choose when to use it. Most times I just want a very simple text editor.

Also ok with the same backtick shortcut GitHub has, but the problem is you can't edit text in there. In other words, you need to type everything at once. If you go back in between the backticks, you're adding normal text.

The second issue is that markdown is parsed while you are in the middle of the backtick.

So you type ` and then go to type a word with two underscores before you close that backtick and things end up italic inside the red code.

Ultimately the markdown parsing makes it impossible to do anything other than use a code block if you have multiple underscores in a line. It's a way big issue actually. I know I just rattled off  what are a few different issues, sorry.

_Originally posted by @tmaiaroto in https://github.com/AppFlowy-IO/AppFlowy/issues/3628#issuecomment-1783153626_
            

## Impact

All users who want to use AppFlowy as a simple text-based notes app. OR
All users who want to disable markdown syntax in some use-cases.

**Comment by annieappflowy** [comment] 2023-12-21 18:06
#3964

**Comment by Xazin** [comment] 2024-04-08 11:18
We have the `\` backslash to ignore markdown, so this is how it would look:
```
Hello world, and `\_welcome_ to appflowy`.
```
Which should end up looking like this:

Hello world, and `_welcome_ to appflowy`.

**Comment by annieappflowy** [comment] 2024-08-10 07:25
cmd / ctrl z to undo markdown

**Comment by Xazin** [comment] 2024-10-03 00:53
Closing this for now, as Annie mentions above, you can use `CTRL/CMD + Z` to undo the latest applied markdown, and you can continue to complete your text as intended.

We will most likely make improvements to this behavior in the future.

**Closed by Xazin** 2024-10-03 00:53 UTC
Labels: new feature, editor, Q2 24
