### ISSUE TITLE
[FR] Global Search

### ISSUE THREAD

**Issue by Zeit08** [AppFlowy-IO/AppFlowy#4189] opened 2023-12-21 10:13 UTC
### Description

An icon with a global search in the toolbar above everything can let users find some texts quickly. Global search means that if I type "mango" on it, it will search that word in every file and show me which files have it.

### Impact

ability to find the word they used somewhere but they don't remember where.

### Additional Context

I took the idea from the markdown app Zettlr which I currently use.

**Comment by Xazin** [comment] 2023-12-21 14:52
Duplicate of #2232 #2315

**Closed by Xazin** 2023-12-21 14:52 UTC
