### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by emRival** [AppFlowy-IO/AppFlowy#2119] opened 2023-03-27 08:29 UTC
### Bug Description

when I add a checklist in my ToDo and I create a new ToDo, there are still attributes from the previous todo and when deleted or changed to a text attribute, all checklists in the previous todo that were created will disappear. I hope that every ToDo that I make can use different attributes

### How to Reproduce

create a ToDo that can store its respective attributes

### Expected Behavior

when I add a checklist in my ToDo and I create a new ToDo, there are still attributes from the previous todo and when deleted or changed to a text attribute, all checklists in the previous todo that were created will disappear. I hope that every ToDo that I make can use different attributes

### Operating System

Macbook Pro M1

### AppFlowy Version(s)

Version 0.1.1

### Screenshots

<img width="797" alt="Screenshot 2023-03-27 at 3 25 45 PM" src="https://user-images.githubusercontent.com/90138726/227884771-66443da6-9066-4808-b5aa-e3e93a707b2c.png">
<img width="800" alt="Screenshot 2023-03-27 at 3 26 05 PM" src="https://user-images.githubusercontent.com/90138726/227884885-6ca9bd5f-bbd7-4df8-9556-043cd42e067c.png">

**Comment by annieappflowy** [comment] 2023-03-27 13:00
Hi @emRival , thanks for reporting. This is a duplicate of https://github.com/AppFlowy-IO/AppFlowy/issues/1692
We'll improve this feature soon.

**Closed** 2023-03-27 13:22 UTC
