### ISSUE TITLE
[FR] Renaming "No Status"

### ISSUE THREAD

**Issue by ItsJustTee** [AppFlowy-IO/AppFlowy#1733] opened 2023-01-20 20:33 UTC
### Description

Good day. I am using AppFlowy for Bug Tracking, Software Ideas and Game Ideas and I am thoroughly impressed with the Software. I do feel like there is a missing feature which is the option to rename Categories.

### Impact

By allowing users to rename categories, it will improve the organization of Current Bugs and allow us to work in an effiecient manner.

### Additional Context

I am currently using AppFlowy to have an updated list of GlimeshTV Bugs and this feature would be a godsent for me as a fellow Bug Hunter.

**Comment by annieappflowy** [comment] 2023-01-22 02:42
Hi @MrTeeXD , I'm glad that you find AppFlowy helpful, and thanks for sharing your use cases with us, super valuable!
Can you elaborate on renaming Categories? I'm not sure which feature you are referring to. I'd like to improve AppFlowy and make it better for you :)

**Comment by annieappflowy** [comment] 2023-01-26 15:44
https://user-images.githubusercontent.com/12026239/214880377-3d9038c5-6f85-462b-8161-2967d1d08916.mp4

I see. I made a recording on how to rename group-by values. Please check and see if this resolves your problem.
"No Status" is not able to rename at the moment, although we can make it a feature request to consider.

**Comment by MrTeeXD** [comment] 2023-01-26 16:51
Ahh, awesome. I did also find a weird bug where If I create a new category and then delete it, that New Category still shows in the Board View causing me to create a fresh new Board List.

**Comment by annieappflowy** [comment] 2023-01-28 08:11
Thanks, @MrTeeXD . I'm able to reproduce the bug. Will assign folks to fix it soon.

**Comment by annieappflowy** [comment] 2023-02-07 13:25
"By the way, if I were be able to rename the No Status board, I'd probably make it notes, so that I can refer to notes when I'm working on my LUA script
I think all boards should be renameable including No Status
Even if people don't use it, it just makes it more customisable
I'm sort of speaking for the people here, which I don't know whether I should because I don't know what people think, but yeah." by civil on Discord

**Comment by annieappflowy** [comment] 2023-02-21 07:22
1. Enable users to hide No Status.
2. Enable users to rename "No Status" while giving visual clues to users so they know this is a "No Status" column.

**Comment by Adda0** [comment] 2023-06-19 05:52
> 1. Enable users to hide No Status.
>  2. Enable users to rename "No Status" while giving visual clues to users so they know this is a "No Status" column.

I confirm that, as one of the aforementioned “people”, would appreciate both these features. It is a little thing, but it would improve UX a lot, I believe.

As of now, “No Status” is a developer naming revealing the internal implementation (an item needs a tag to categorize it, or it has no tag). The user has a different workflow and though process, I think. They create a new note, example, though, and later they want to categorize it as per their own organization. They should not think about having a tag or having none (resembling `Option<Tag>`), they should instead think about the note being categorized or not. And that can be simply resolved by enabling either hiding the “no status” category entirely, or allowing them to rename it to something that suits their needs.

**Closed** 2023-12-24 01:22 UTC
Labels: kanban board

**Comment by YourMaster77W** [comment] 2024-08-11 06:51
August 2024 and there still is no horizontal scrollbar..  haha.  But I did just learn that I can use Scroll + Shift to move the screen.  Hope I don't forget tomorrow..  I am horrible with these kinds of shortcuts.
But don't get me wrong..  I love the fact that this company can bring some kind of competition to Trello.
