### ISSUE TITLE
[Bug] The program cannot run properly.

### ISSUE THREAD

**Issue by taylormao** [AppFlowy-IO/AppFlowy#2152] opened 2023-03-31 00:48 UTC
### Bug Description

I am using the operating system Windows 10 LTSC Version 21H2. I downloaded AppFlowy_0.1.2_windows-x86_64.zip from https://github.com/AppFlowy-IO/appflowy/releases. After I extracted it and clicked on AppFlowy.exe, a white screen appeared without any buttons. This state persisted for about 30 seconds, and then the application suddenly disappeared. In other words, I cannot use this program normally. I am very sad about this.

### How to Reproduce

ddownload and unzip ，and click the appflowy.exe

### Expected Behavior

I am using the operating system Windows 10 LTSC Version 21H2. I downloaded AppFlowy_0.1.2_windows-x86_64.zip from https://github.com/AppFlowy-IO/appflowy/releases. After I extracted it and clicked on AppFlowy.exe, a white screen appeared without any buttons. This state persisted for about 30 seconds, and then the application suddenly disappeared. In other words, I cannot use this program normally. I am very sad about this.

### Operating System

 Windows 10 LTSC Version 21H2

### AppFlowy Version(s)

AppFlowy_0.1.2

### Screenshots

![error](https://f002.backblazeb2.com/file/images-taylor-pc/ShareX/2023/03/AppFlowy_jLNTRQQnbq.png)

nothing,and 30s later, the app shade down

### Additional Context

"Is there any missing runtime dependency and how to address it?"

**Comment by LucasXu0** [comment] 2023-03-31 05:35
@a-wallen Can you help to check this issue?

**Comment by taylormao** [comment] 2023-03-31 09:35
> @a-wallen Can you help to check this issue?

thank you

**Comment by a-wallen** [comment] 2023-04-02 01:09
I'm unable to reproduce this on Windows 11 and on Windows 10 (22H2). @taylormao are you able to update your computer and try again or, send us additional information from Start > Settings > System > About.

**Comment by taylormao** [comment] 2023-04-02 01:47
> I'm unable to reproduce this on Windows 11 and on Windows 10 (22H2). @taylormao are you able to update your computer and try again or, send us additional information from Start > Settings > System > About.
---
I have shared the error file that occurred during runtime in another issue.

#2163  This issue contains more detailed runtime errors.

Here is a screenshot of my operating system information.

![](https://f002.backblazeb2.com/file/images-taylor-pc/ShareX/2023/04/ApplicationFrameHost_CFyRDbitjJ.png)

I am a user in China and I am very much looking forward to the recognition of your products here in China.

thank you [a-wallen](https://github.com/a-wallen) @a-wallen

**Comment by taylormao** [comment] 2023-04-02 01:59
@a-wallen ,I traced the error message. The content is as follows.
```shell
AppFlowy.exe thread '<unnamed>' panicked at 'called Result::unwrap() on an Err value: Error(R2D2(Error(Some("Some kind of disk I/O error occurred"))), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })', flowy-sqlite\src\kv\kv.rs:91:42
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
```

**Comment by a-wallen** [comment] 2023-04-04 00:25
I don't have a computer where I'd like to install Windows 10 LTSC, so I will remove my assignment to this issue as I cannot reproduce with Windows 10 22H2 and Windows 11.

Although I'm unable to reproduce it, it looks like the error is a SQLITE_IOERR from libsqlite3 (see [errors.rs](https://docs.rs/libsqlite3-sys/0.9.0/src/libsqlite3_sys/error.rs.html#172)) and has to do with the way that we set our `journal_mode`. It looks like the [default configuration is set to WAL](https://github.com/AppFlowy-IO/AppFlowy/blob/cf93e92e64ed4b4320d4dbcab4af5f8c5c3f8e53/frontend/rust-lib/flowy-sqlite/src/sqlite/pool.rs#L119-L128). Others have run into [similar problems](https://github.com/askmike/gekko/issues/1375#issuecomment-347717835) on Windows 10 with the same `journal_mode` settings and looks like it was fixed by changing the journal mode. 

Nonetheless, I cannot reproduce the issue, so I can't confirm if those changes are adequate.

**Comment by taylormao** [comment] 2023-04-04 01:11
Can this error be fixed in the next release version? I am not an open source contributor, but a user from China. I hope this error can be fixed in the subsequent versions. Thank you very much for your clarification.

**Comment by a-wallen** [comment] 2023-04-04 01:54
I'd love to fix this, but I can't, given my lack of resources. I'll reach out on Discord to find a contributor that might be running Windows 10 LTSC. Unfortunately, I don't think you can use AppFlowy unless someone contributes a fix or if you update your operating system.

**Comment by annieappflowy** [comment] 2023-06-12 12:36
Please try the latest [release](https://github.com/AppFlowy-IO/AppFlowy/releases) and reopen if you still run into the issue.

**Closed** 2023-06-12 12:35 UTC
Labels: bug
