### ISSUE TITLE
[Bug] Option bar truncated

### ISSUE THREAD

**Issue by speed2exe** [AppFlowy-IO/AppFlowy#4103] opened 2023-12-06 05:28 UTC
### Bug Description

after pressing "/refer.." to select Referenced Document, cannot type filter out selection choice.
<img width="461" alt="ss1" src="https://github.com/AppFlowy-IO/AppFlowy/assets/33050391/c78e65c8-0c1a-4580-868b-fafcf8038588">

### How to Reproduce

<img width="361" alt="ss2" src="https://github.com/AppFlowy-IO/AppFlowy/assets/33050391/0a91dfd1-83f1-4359-8a48-d426e8381b40">
press "/referenced doc", press enter

### Expected Behavior

keypress should fuzzy find and filter out relevant document names

### Operating System

Windows 11

### AppFlowy Version(s)

0.3.9.1

**Comment by Xazin** [comment] 2023-12-08 13:36
Duplicate of #3841

**Closed by Xazin** 2023-12-08 13:36 UTC
