### ISSUE TITLE
[Bug] Backspace and Arrow Keys Not Working on AppFlowy for Linux (Manjaro/Arch)

### ISSUE THREAD

**Issue by ReeeoooN** [AppFlowy-IO/AppFlowy#6542] opened 2024-10-14 10:42 UTC
### Bug Description

I am experiencing an issue with the AppFlowy application on Linux (Manjaro/Arch) where the Backspace and Arrow keys are not functioning properly. This problem occurs in version 0.7.1, but I did not encounter this issue in version 0.6.9.

### How to Reproduce

1. Install AppFlowy version 0.7.1 on a Manjaro/Arch Linux system.

2. Open the application.

3. Try using the Backspace key and the Arrow keys on text.

### Expected Behavior

The Backspace key should delete the character before the cursor, and the Arrow keys should navigate through the text.

### Operating System

Manjaro/Arch Linux

### AppFlowy Version(s)

0.7.1

### Additional Context

Thank you for looking into this issue!

**Comment by LucasXu0** [comment] 2024-10-14 11:11
Hi, @ReeeoooN. Did you modify the shortcut keybindings in the settings page before?

**Comment by ReeeoooN** [comment] 2024-10-14 11:39
> Hi, @ReeeoooN. Did you modify the shortcut keybindings in the settings page before?

Yes, I changed the key combination. If I change it to a random key and then set it back to the original one, a notification about overwriting the keys appears. If I overwrite it, the backspace key temporarily works when I want to delete text.

![image](https://github.com/user-attachments/assets/4577f0b7-13d4-4cad-abde-092543bbd665)
![image](https://github.com/user-attachments/assets/3fcd8592-4ac1-4474-9e94-98372eddbd7d)

**Comment by LucasXu0** [comment] 2024-10-14 12:36
@ReeeoooN Could you reset the `backspace` and `arrow key` keybindings to default? Your issue was caused by key conflicts. We're working on fixing it.

**Comment by ReeeoooN** [comment] 2024-10-14 13:55
@LucasXu0 The reset helped for now, but usually the error reoccurs after some time. In any case, thank you; the bug isn't critical for me since I have built the previous release and I'm using it. I will be waiting for the next release with the fix!

**Comment by andradei** [comment] 2024-10-14 21:37
This is happening on Arch linux, latest flatpak version 0.7.1.
No keybindings changed. Using local storage (no cloud).

**Comment by LucasXu0** [comment] 2024-10-15 05:38
> It seems to happen (for me) on kanban/grid views only.

Hi, @andradei. Is the "kanban/grid view" you mean the linked database view in a doc or the single database page?

**Comment by matheodrd** [comment] 2024-10-17 05:51
I have the same problem on Windows 10, using version 0.7.1.
With default configuration, except I'm using local storage.

When I want to edit the content of a card in a Kanban (linked or not), I can't use the _backspace_ key (except on `+` characters or by using CTRL+Backspace) and the _left_ and _up_ arrow keys.

![image](https://github.com/user-attachments/assets/5bd44dd4-3d60-4f0f-9047-83fc4fc093d9)

**Comment by LucasXu0** [comment] 2024-10-17 06:00
@matheodrd Thanks for reporting. It will be resolved in the upcoming release.

**Comment by alyvusal** [comment] 2024-10-20 12:06
> This is happening on Arch linux, latest flatpak version 0.7.1. No keybinding changes. Using local storage (no cloud).
> 
> It seems to happen (for me) on kanban/grid views only. The bug is random. At first, backspace and arrows were not working.
> 
> After restarting the app and moving the kanban board to another page, backspace, right and down arrows worked but up and left didn't. PgUP worked and PgDown didn't.

Same happens for me as described here on Ubuntu 24.04 with AppImage

**Comment by mleczakm** [comment] 2024-10-20 20:47
I'm having same issue on Manjaro, version 0.7.1, installed by flatpak.

**Comment by alyvusal** [comment] 2024-10-22 09:34
Works now on v0.7.2

**Closed** 2024-10-31 15:31 UTC
