### ISSUE TITLE
[Bug] Show the good version of the app and not 1.0.0

### ISSUE THREAD

**Issue by yodatak** [AppFlowy-IO/AppFlowy#1464] opened 2022-11-17 13:07 UTC
### Bug Description

For now we can't know the app version it show only 1.00 and not the real version of the app

### How to Reproduce

Go tho the ? in the right corner and it show 1.0.0

### Expected Behavior

show the reeal version

### Operating System

Windows

### AppFlowy Version(s)

don't know because of this bug

**Comment by annieappflowy** [comment] 2022-11-18 03:00
Thanks for reporting this issue. Duplicate of https://github.com/AppFlowy-IO/AppFlowy/issues/1365

**Closed by annieappflowy** 2022-11-18 03:00 UTC
