### ISSUE TITLE
on CentOS8, Failed to load dynamic library 'libdart_ffi.so'

### ISSUE THREAD

**Issue by aihuasxy** [AppFlowy-IO/appflowy#184] opened 2021-12-20 05:58 UTC
downlaod "AppFlowy-linux-x86.tar.gz" and extract to foloder.
failed to start with "./app_flowy"

```
[AppFlowy]$ ./app_flowy
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'libdart_ffi.so': /lib64/libm.so.6: version `GLIBC_2.29' not found (required by AppFlowy/lib/libdart_ffi.so)
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:12)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:23)
#2      _open (package:flowy_sdk/ffi.dart:19)
#3      _dl (package:flowy_sdk/ffi.dart:10)
#4      _set_stream_port (package:flowy_sdk/ffi.dart)
#5      set_stream_port (package:flowy_sdk/ffi.dart)
#6      FlowySDK.init (package:flowy_sdk/flowy_sdk.dart:23)
#7      InitRustSDKTask.initialize.<anonymous closure> (package:app_flowy/startup/tasks/init_sdk.dart:23)
#8      InitRustSDKTask.initialize.<anonymous closure> (package:app_flowy/startup/tasks/init_sdk.dart:19)
#9      _rootRunUnary (dart:async/zone.dart:1436)
<asynchronous suspension>
#10     AppLauncher.launch (package:app_flowy/startup/launcher.dart:36)
<asynchronous suspension>
```

**Comment by PabloCastellano** [comment] 2021-12-20 13:27
Duplicate of https://github.com/AppFlowy-IO/appflowy/issues/180

**Comment by MikeWallaceDev** [comment] 2021-12-20 16:23
Duplicate of #180

Sorry Pablo, I had to repeat this because the Git flow will only work if you have write access to the repo :)  Thanks for marking it!

**Comment by MikeWallaceDev** [comment] 2021-12-20 16:25
I said that, and the flow didn't even work!  #face_palm.
Let me try that again.  Maybe it didn't work because I added text?

**Comment by MikeWallaceDev** [comment] 2021-12-20 16:25
Duplicate of #180

**Closed by MikeWallaceDev** 2021-12-20 16:25 UTC
