### ISSUE TITLE
[FR] Ability to rename document titles with F2 shortcut

### ISSUE THREAD

**Issue by Joso997** [AppFlowy-IO/AppFlowy#3623] opened 2023-10-05 11:16 UTC
### Description

Ability to rename document titles with F2 shortcut

### Impact

Well, it is a universal shortcut for renaming, at least in Windows.

**Comment by Joso997** [comment] 2023-10-05 12:39
Additionally, it would be cool if the main heading of the page would also be the title of the page. The inner workings of this would have to be customized in the context of the application so I can't specify how it should work

**Comment by amgenene** [comment] 2023-10-05 15:14
This sounds like a fun thing to work on, if nobody has picked it up could I take a crack at it? @Joso997 @MayurSMahajan

**Comment by MayurSMahajan** [comment] 2023-10-05 15:47
Sure @amgenene. Happy coding!

**Comment by Xazin** [comment] 2023-10-10 06:07
This is a duplicate of #3490 - Consider assigning Amgenene there and then closing this @MayurSMahajan @amgenene

**Comment by MayurSMahajan** [comment] 2023-10-11 18:13
oh my bad

**Comment by MayurSMahajan** [comment] 2023-10-11 18:15
When I type @amgenene name in the assignee' search bar, it doesn't show up, @amgenene can you please comment on that issue #3490

**Comment by Xazin** [comment] 2023-10-27 14:45
> @Xazin can I work on this?

Sure @SaadTanveer14, I've assigned you. Let us know if you need assistance.

**Comment by SaadTanveer14** [comment] 2023-10-27 15:33
> > @Xazin can I work on this?
> 
> Sure @SaadTanveer14, I've assigned you. Let us know if you need assistance.

I will Thanks

**Comment by Xazin** [comment] 2024-01-21 19:02
Since no one is working on this, closing as duplicate of #3490

**Closed by Xazin** 2024-01-21 19:02 UTC
Labels: shortcuts, 2024
