### ISSUE TITLE
[Bug] Blank page

### ISSUE THREAD

**Issue by rishabhgusain6** [AppFlowy-IO/AppFlowy#65] opened 2021-11-21 15:05 UTC
**Describe the bug**
So, I wrote notes in a page withs some highlights yesterday. Today when I opened the app, the page opened and showed the title but no content of that page was visible. There was only a blank white page there. I tried restarting the app & PC both multiple times but it is still the same! I left it open for some time too but nothing happened!

**To Reproduce**
1. Open the app
2. Click on the page/ or if u closed the app with that page last time, It will open from that page

**Expected behavior**
I expected the app to open with the page on which I closed the app last time with all the things which I wrote there visible to me clearly as it was written there

**Screenshots**
![image](https://user-images.githubusercontent.com/73269561/142767391-f8dc5e46-d098-4981-a36b-65fc3499cec0.png)

**Desktop**
 - Windows 11
 - Edge 98
 - 0.0.2

**Comment by annieappflowy** [comment] 2021-11-21 15:16
Hi, reproduced on Windows. Looking into it. Thank you!

**Comment by rishabhgusain6** [comment] 2021-11-21 17:23
> Hi, reproduced on Windows. Looking into it. Thank you!

Thanks! I am eager to write my feedback on that page once the issue is solved and use the app again normally!

**Comment by Hari-07** [comment] 2021-11-23 07:06
Was this fixed? I tried to reproduce it by writing a title and text on a new page, then rebooted system and when I came back nothing was changed

**Comment by rishabhgusain6** [comment] 2021-11-23 14:20
> 

IDK about others, maybe something else happened too which I don't remember or may be only some/me are facing this issue

**Comment by appflowy** [comment] 2021-11-24 03:36
Hi @rishabhgusain6, I can reproduce it on my windows 11. It takes time to figurate it out.

**Comment by Hari-07** [comment] 2021-11-24 03:48
Is it possible it's a windows 11 thing? Cos I'm on 10, but not really sure if something like this could be OS related

**Comment by DuranceX** [comment] 2021-12-08 14:12
I‘m on Windows 10, I just tried this app and found the "Read me" page became a blank page just like this, just after I close and reopen the app.

**Comment by appflowy** [comment] 2022-01-18 14:01
@rishabhgusain6 This bug have been fixed in main branch and will be included in the release v0.0.3.

**Comment by methbkts** [comment] 2022-01-29 02:32
Same bug on MacOS Monterey 12.2 (Intel), I don't even need to restart the app, changing pages is enough

**Comment by annieappflowy** [comment] 2022-01-29 12:33
Thank you all for reporting the issue and following us! v0.0.3-beta will be released tomorrow

**Comment by OpenWaygate** [comment] 2022-07-23 12:57
Windows 11 22H2 OS Build 22622.436
Microsoft Edge Version 103.0.1264.71 (Official build) (64-bit)
AppFlowy Version v0.0.4

![image](https://user-images.githubusercontent.com/27287694/180605781-7bde2fb0-908e-4f80-a6eb-ebbc3428fe06.png)

**Comment by apomalyn** [comment] 2022-07-23 13:21
@OpenWaygate do you have the issue after creating a new page? Or when opening the application?

**Comment by OpenWaygate** [comment] 2022-07-23 13:36
> @OpenWaygate do you have the issue after creating a new page? Or when opening the application?

Opening the application. 

I restart my pc and open appflowy again, now the startup page appears, click **Let's Go** gives no response but the following two links can redirect me to browser.

![image](https://user-images.githubusercontent.com/27287694/180607243-693160fc-a043-43ad-a86c-a0278569efeb.png)

**Comment by polypixeldev** [comment] 2022-12-30 03:39
I am unable to reproduce this issue on the latest main branch as of now (commit aa5f052ecf30a1fb7b3fe61d3cdc050919d1b292). I think that this issue can now be closed @annieappflowy

**Comment by annieappflowy** [comment] 2022-12-31 02:59
Thanks @polypixeldev 
I'm closing this issue

**Closed by annieappflowy** 2022-12-31 02:59 UTC
Labels: bug
