### ISSUE TITLE
[Bug] Browse Path window doesn't open on window manager(dwm)[Bug] 

### ISSUE THREAD

**Issue by shareghzade** [AppFlowy-IO/AppFlowy#2335] opened 2023-04-23 13:55 UTC
### Bug Description

Hi,
when i want to select path to my files to be located and when i click on browse button it doesn't work. even "open an existing folder"  doesn't work

### How to Reproduce

.

### Expected Behavior

expected behavior is to open window to select/create folder

### Operating System

Arch Linux

### AppFlowy Version(s)

0.1.2

**Comment by annieappflowy** [comment] 2023-04-24 02:38
Likely related to https://github.com/AppFlowy-IO/AppFlowy/issues/2300

**Comment by a-wallen** [comment] 2023-04-27 22:25
@shareghzade, if this is the same issue as #2300, please let us know so we can consolidate these issues and increase awareness of this bug.

**Comment by shareghzade** [comment] 2023-05-03 16:03
@a-wallen yes it is the same as #2300

**Comment by a-wallen** [comment] 2023-05-03 20:33
Thanks @shareghzade, closing as a duplicate of #2300.

**Closed by a-wallen** 2023-05-03 20:33 UTC
Labels: bug, data sync
