### ISSUE TITLE
[FR] IOS and Android support

### ISSUE THREAD

**Issue by antime** [AppFlowy-IO/AppFlowy#1547] opened 2022-12-08 03:23 UTC
### Description

Android and IOS app support

### Impact

all users

**Comment by Cosmopal** [comment] 2023-03-25 18:10
Is this open for public contribution? I'd like to contribute to this feature.

**Comment by annieappflowy** [comment] 2023-03-27 09:09
I believe there are many areas you can contribute to the mobile versions.
@LucasXu0 will create a few first-time friendly issues on mobile

**Comment by gianpaj** [comment] 2023-06-10 16:38
duplicate of  https://github.com/AppFlowy-IO/appflowy-editor/issues/68 ?

**Comment by annieappflowy** [comment] 2023-06-11 03:42
It has overlap but not exactly the same. appflowy_editor is a subset of AppFlowy. We'll support mobile for appflowy_editor first and then AppFlowy.

**Comment by annieappflowy** [comment] 2024-01-23 01:34
AppFlowy Mobile is available to download from https://appflowy.io/download#ios-and-android

**Closed by annieappflowy** 2024-01-23 01:34 UTC
Labels: mobile, 2024
