### ISSUE TITLE
[FR] Grid : Being able to see hidden properties in Details page

### ISSUE THREAD

**Issue by VenomSupreme** [AppFlowy-IO/AppFlowy#2882] opened 2023-06-22 10:09 UTC
### Description

When we open details page of a row in grid, we should be able to see All the properties of that row. Currently the Hidden properties are also hidden in details so we have to go back and "unhide" just to see them in details page.

### Impact

People with multiple properties in Grid view who choose to only see Most Important in grid view and hide others. But having to unhide them just to see them in details defeats the purpose of hiding them in first place.

Details page is meant to show all the details and we should be able to see hidden properties too in that.

**Comment by richardshiue** [comment] 2023-06-22 10:23
Closing as duplicate of #2394

**Closed by richardshiue** 2023-06-22 10:23 UTC

**Comment by annieappflowy** [comment] 2023-10-13 08:27
Hi @VenomSupreme , we enabled showing hidden properties in the row detail page in v0.3.4
<img width="697" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/843f2a4b-cc8d-47d3-b9a1-3adfb8f01d45">
