### ISSUE TITLE
[Bug] Inline Page reference showing Unusual Behaviour 

### ISSUE THREAD

**Issue by Mukund-Tandon** [AppFlowy-IO/AppFlowy#3198] opened 2023-08-14 13:04 UTC
### Bug Description

https://github.com/AppFlowy-IO/AppFlowy/assets/71614009/1baecf3f-d3b2-4ea4-9e9d-05ebb39c4720

As we can see in the video the inline page reference is showing unusual behaviour . This happens only sometime not always

### How to Reproduce

- make an inline pages 
- start typing in front of that page 
- the cursor will show some unusual behaviour and sometime there would be a copy of inline page automatically created in front of the cursor

### Expected Behavior

We should be able to type normally in front of inline page reference

### Operating System

MacOs

### AppFlowy Version(s)

0.2.9

**Comment by Xazin** [comment] 2023-08-14 13:06
Assigning this to myself for now, on my current feature branch, I have completely rewritten the majority of this feature.

Once I'm done and it's merged I'll revisit this issue.

**Comment by Xazin** [comment] 2023-10-25 17:40
Hey @Mukund-Tandon, on the newest version of AppFlowy, are you able to reproduce this?

I've rewritten large parts of how the menu works since this was reported, and thus it might either be fixed, or have new issues.

Let me know :+1:

**Comment by Mukund-Tandon** [comment] 2023-10-28 14:16
> Hey @Mukund-Tandon, on the newest version of AppFlowy, are you able to reproduce this?
> 
> I've rewritten large parts of how the menu works since this was reported, and thus it might either be fixed, or have new issues.
> 
> Let me know 👍

Now it is behaving like this - 

https://github.com/AppFlowy-IO/AppFlowy/assets/71614009/4ee401f2-e1e9-452a-bf45-a20c9765555e

**Comment by Xazin** [comment] 2023-10-28 17:17
> > Hey @Mukund-Tandon, on the newest version of AppFlowy, are you able to reproduce this?
> > I've rewritten large parts of how the menu works since this was reported, and thus it might either be fixed, or have new issues.
> > Let me know 👍
> 
> Now it is behaving like this -
> 
>  Screen.Recording.2023-10-28.at.7.44.51.PM.mov

Thanks, I'll see if I can reproduce.

**Comment by annieappflowy** [comment] 2023-12-22 19:13
I think the issue was fixed.
Please feel free to re-open if you still see this issue

**Closed by annieappflowy** 2023-12-22 19:13 UTC
