### ISSUE TITLE
Cannot run on Ubuntu22.4

### ISSUE THREAD

**Issue by JamesUmmec** [AppFlowy-IO/AppFlowy#566] opened 2022-06-18 13:35 UTC
When running on Ubuntu22.4 (linux x86_64), the window stay blank and cannot show anything.

- Operating system: Ubuntu22.4, x86_64 GNU/Linux

Here are cli output when running this app:
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'libdart_ffi.so': libssl.so.1.1: cannot open shared object file: No such file or directory
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:12)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:23)
#2      _open (package:flowy_sdk/ffi.dart:23)
#3      _dl (package:flowy_sdk/ffi.dart:10)
#4      _set_stream_port (package:flowy_sdk/ffi.dart)
#5      set_stream_port (package:flowy_sdk/ffi.dart)
#6      FlowySDK.init (package:flowy_sdk/flowy_sdk.dart:32)
#7      InitRustSDKTask.initialize.<anonymous closure> (package:app_flowy/startup/tasks/rust_sdk.dart:13)
#8      InitRustSDKTask.initialize.<anonymous closure> (package:app_flowy/startup/tasks/rust_sdk.dart:12)
#9      _rootRunUnary (dart:async/zone.dart:1434)
<asynchronous suspension>
#10     InitRustSDKTask.initialize (package:app_flowy/startup/tasks/rust_sdk.dart:12)
<asynchronous suspension>
#11     AppLauncher.launch (package:app_flowy/startup/startup.dart:99)
<asynchronous suspension>
```

**Comment by jpastolfo** [comment] 2022-07-15 12:46
I ran into the same situation and found that a problem with packaging in 22.04 causes the issue. A more detailed discussion can be found [here](https://stackoverflow.com/questions/72133316/ubuntu-22-04-libssl-so-1-1-cannot-open-shared-object-file-no-such-file-or-di).

Just use:

```
wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1l-1ubuntu1.6_amd64.deb

sudo dpkg -i libssl1.1_1.1.1l-1ubuntu1.6_amd64.deb
```

 Works fine for me (for now)!

**Comment by JamesUmmec** [comment] 2022-07-19 01:23
> @JamesUmmec are you still having the issue?

Sorry, I'm now using arch rather than ubuntu. 😂

**Comment by annieappflowy** [comment] 2022-07-19 02:53
Ah ok, if you are no longer having issues with running AppFlowy on your device, please close this issue. Thanks

**Comment by theboywhomakesgames** [comment] 2022-07-19 11:28
Would it be helpful if I work on a snap package of AppFlowy?

**Comment by tliebig** [comment] 2022-07-19 20:34
The problem persists - I have the very same error on my Fedora 36 after extracting the tar file, moving the AppFlowy directory to /opt/ and trying to start as a regular user instead of admin:

`[tliebig@FEDORA-28 ~]$ cd /opt/AppFlowy/
[tliebig@FEDORA-28 AppFlowy]$ ./app_flowy 
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'libdart_ffi.so': libssl.so.1.1: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:12)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:23)
#2      _open (package:flowy_sdk/ffi.dart:23)
#3      _dl (package:flowy_sdk/ffi.dart:10)
#4      _set_stream_port (package:flowy_sdk/ffi.dart)
#5      set_stream_port (package:flowy_sdk/ffi.dart)
#6      FlowySDK.init (package:flowy_sdk/flowy_sdk.dart:32)
#7      InitRustSDKTask.initialize.<anonymous closure> (package:app_flowy/startup/tasks/rust_sdk.dart:13)
#8      InitRustSDKTask.initialize.<anonymous closure> (package:app_flowy/startup/tasks/rust_sdk.dart:12)
#9      _rootRunUnary (dart:async/zone.dart:1434)
<asynchronous suspension>
#10     InitRustSDKTask.initialize (package:app_flowy/startup/tasks/rust_sdk.dart:12)
<asynchronous suspension>
#11     AppLauncher.launch (package:app_flowy/startup/startup.dart:99)
<asynchronous suspension>

`

**Comment by manV** [comment] 2022-07-21 04:02
I also have same issue on Fedora 36.

**Comment by FinnRG** [comment] 2022-07-21 12:52
@tliebig @manV Please search the issue tracker before posting new questions. You need to install another library for Fedoras 36. you can find instructions here: https://github.com/AppFlowy-IO/AppFlowy/issues/112#issuecomment-1133666925

**Comment by FilBot3** [comment] 2022-07-21 19:36
I had the same problem on Fedora 36 Silverblue. However, installing `sudo rpm-ostree install openssl-devel` did not solve the issue.

On Ubuntu, you'd have to find the libraries that provide the libssl-dev packages, I believe.

This dependency should be called out on the README for now, or somewhere else. Otherwise, if this can be packaged as a Flatpak, I think you'd reach a larger, much more accepting audience. Obsidian is nice, but it's closed source, Joplin is nice, but everything is in one bucket.

**Comment by FilBot3** [comment] 2022-07-21 19:38
Should be solved here: Issue https://github.com/AppFlowy-IO/AppFlowy/issues/112 but the version of OpenSSL I have installed is supposedly much newer? 

```bash
➜  AppFlowy 
> openssl version
OpenSSL 3.0.5 5 Jul 2022 (Library: OpenSSL 3.0.5 5 Jul 2022)
```

**Comment by annieappflowy** [comment] 2022-07-22 03:22
@FilBot3 thanks for your input. We decide to work on supporting Flatpak. Please follow this thread for the update: https://github.com/AppFlowy-IO/AppFlowy/issues/175
RE: update the dependency, can you clarify what dependencies for which system?
We're open to documentation contributions. Maybe you can directly edit it and submit a PR. It can probably goes here: https://github.com/AppFlowy-IO/AppFlowy-Docs/blob/main/essential-documentation/install-appflowy/installation-methods/mac-windows-linux-packages/installing-on-linux.md

**Comment by MikeWallaceDev** [comment] 2022-07-23 14:56
I will check this out. We problably need to add to the documentation.
Note to self: also look at #112

**Comment by eurythmia** [comment] 2022-08-01 06:27
confirmed on Pop!_OS 22.04 LTS (ostensibly, Ubuntu 22.04)

fixed with `sudo apt install libssl1.1` (because the lib is in the official repos)

**Comment by eurythmia** [comment] 2022-08-01 06:32
> Should be solved here: Issue #112 but the version of OpenSSL I have installed is supposedly much newer?
> 
> ```shell
> ➜  AppFlowy 
> > openssl version
> OpenSSL 3.0.5 5 Jul 2022 (Library: OpenSSL 3.0.5 5 Jul 2022)
> ```

for fedora you should be able to resolve your issue with `sudo dnf install openssl1.1` IIRC (it's been a few months since I looked, `dnf search ssl1.1` should give you some ideas, if not try the `dnf search` again with `libssl1.1` and `openssl`)

**Comment by juliendf** [comment] 2022-08-10 13:57
libssl1.1_1.1.1l-1ubuntu1.6_amd64.deb is 404

Works with : 
wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb

**Comment by IcedQuinn** [comment] 2022-12-25 17:07
This problem also happens on Void.

**Comment by oopschen** [comment] 2023-01-18 01:20
Happened on Gentoo.

System Info
`Linux raylaptop 5.15.80-gentoo #14 SMP Sun Jan 8 19:56:27 CST 2023 x86_64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz GenuineIntel GNU/Linux`

OpenSSL Info
`OpenSSL 1.1.1s  1 Nov 2022`

When maually link libssl.so to libssl.so.3, same to libcrypto.so.3, error is:
` ~  [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'libdart_ffi.so': /usr/lib64/libcrypto.so.3: version `OPENSSL_3.0.0' not found (required
by /opt/appflowy-bin/lib/libdart_ffi.so)
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:12)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:23)
#2      _open (package:flowy_sdk/ffi.dart:27)
#3      _dart_ffi_lib (package:flowy_sdk/ffi.dart:10)
#4      _set_stream_port (package:flowy_sdk/ffi.dart)
#5      set_stream_port (package:flowy_sdk/ffi.dart)
#6      FlowySDK.init (package:flowy_sdk/flowy_sdk.dart:32)
#7      InitRustSDKTask.initialize.<anonymous closure> (package:app_flowy/startup/tasks/rust_sdk.dart:24)
#8      InitRustSDKTask.initialize.<anonymous closure> (package:app_flowy/startup/tasks/rust_sdk.dart:23)
#9      _rootRunUnary (dart:async/zone.dart:1434)
<asynchronous suspension>
#10     AppLauncher.launch (package:app_flowy/startup/startup.dart:124)
<asynchronous suspension>
#11     FlowyRunner.run (package:app_flowy/startup/startup.dart:64)
<asynchronous suspension>
#12     main (package:app_flowy/main.dart:25)
<asynchronous suspension>
`

**Comment by PaulLafargue** [comment] 2023-02-24 11:53
Hi

I have the same problem on Ubuntu. The window stays blank. I tried all the things written in this chat, but nothing works. I am not an experienced user, so if there is a solution to this issue, I would be really grateful if somebody could break it down to single steps to follow. Thanks! Hopefully, I can use Appflowy soon!

**Comment by LucasXu0** [comment] 2023-02-24 13:09
Hey, @PaulLafargue. There's a workaround for Ubuntu users. 

```
wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.17_amd64.deb
sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.17_amd64.deb
```

**Comment by PaulLafargue** [comment] 2023-02-25 11:33
Hey @LucasXu0 

Thanks for your help. I tried that, but when I open AppFlowy, the page still remains blank. How can I provide you with more information about my problem?

**Comment by prashant235913** [comment] 2023-03-22 17:17
is this issue open...I want to give it a try

**Comment by LucasXu0** [comment] 2023-03-23 03:13
Hey, @PaulLafargue. Yes. I think we need to embed the libssl into the package to solve this problem.

**Comment by PaulLafargue** [comment] 2023-03-23 07:22
Hey, @LucasXu0 . Well, I didn't open AppFlowy for some weeks after I couldn't solve the problem. But when I opened it some days ago, it suddenly worked. I have no idea why.

**Comment by vincedihub** [comment] 2023-06-21 05:26
Hi, guys,

I was wondering why you don't use a newer version of OpenSSL. The openssl 1.1.1 version is coming to the end of its life (see https://en.wikipedia.org/wiki/OpenSSL) and that's why it's no longer installed by default on new versions of linux distributions.

**Closed** 2023-08-23 06:55 UTC
Labels: documentation, help wanted

**Comment by WaseekSenju** [comment] 2024-05-12 17:25
I am having this problem as well. I followed the [instructions](instructsions). But for some reason even after installing the `libssl1.1_1.1.1` didn't help.

**Operating System**
Ubuntu 22.04.4 LTS

I am getting this output in the debug console:
```
E/flutter ( 8220): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'libdart_ffi.so': dlopen failed: library "libdart_ffi.so" not found
E/flutter ( 8220): #0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:43)
E/flutter ( 8220): #1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
E/flutter ( 8220): #2      _open (package:appflowy_backend/ffi.dart:28:51)
E/flutter ( 8220): #3      _dart_ffi_lib (package:appflowy_backend/ffi.dart:10:38)
E/flutter ( 8220): #4      _dart_ffi_lib (package:appflowy_backend/ffi.dart)
E/flutter ( 8220): #5      _invoke_rust_log (package:appflowy_backend/ffi.dart:163:48)
E/flutter ( 8220): #6      _invoke_rust_log (package:appflowy_backend/ffi.dart)
E/flutter ( 8220): #7      rust_log (package:appflowy_backend/ffi.dart:160:3)
E/flutter ( 8220): #8      Log.info (package:appflowy_backend/log.dart:29:5)
E/flutter ( 8220): #9      _resolveCloudDeps (package:appflowy/startup/deps_resolver.dart:64:7)
E/flutter ( 8220): <asynchronous suspension>
E/flutter ( 8220): #10     DependencyResolver.resolve (package:appflowy/startup/deps_resolver.dart:54:5)
E/flutter ( 8220): <asynchronous suspension>
E/flutter ( 8220): #11     initGetIt (package:appflowy/startup/startup.dart:180:3)
E/flutter ( 8220): <asynchronous suspension>

```
**OPENSSL**
```
❯ openssl version
OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)
```
