### ISSUE TITLE
[Bug] File path cannot open

### ISSUE THREAD

**Issue by superiums** [AppFlowy-IO/AppFlowy#2368] opened 2023-04-27 13:46 UTC
### Bug Description

when choose browser exist notes or create new one, after click browser (choose path)
it reports:
```
Apr 27 21:35:18.671 ERROR ThreadId(22) {"message":"Uncaught platform error"}
{"msg":"Uncaught platform error"}
```

### How to Reproduce

maybe related to os ?

### Expected Behavior

file choose dialog to be shown.

### Operating System

void linux

### AppFlowy Version(s)

0.1.3

### Additional Context

it's easier to add an text box to define path of notes, instead of choose by file chooser.

**Comment by a-wallen** [comment] 2023-04-27 22:24
@superiums, I'm not sure how to reproduce based on your instructions. Could you check the following issues and see if this one is the same?
https://github.com/AppFlowy-IO/AppFlowy/issues/2335
https://github.com/AppFlowy-IO/AppFlowy/issues/2300

**Comment by superiums** [comment] 2023-04-29 02:51
> @superiums, I'm not sure how to reproduce based on your instructions. Could you check the following issues and see if this one is the same? #2335 #2300

yes , it's same as #2300.  i'm also on wm instead of dm. i'm using wayfire as my wm.
(not very similar with #2335)

**Comment by a-wallen** [comment] 2023-04-30 20:53
Ok I will close this as a duplicate of #2335

**Closed by a-wallen** 2023-04-30 20:53 UTC
Labels: bug, platform-linux
