### ISSUE TITLE
[Bug] login with github account，missing field `icon` at line 1 column 540

### ISSUE THREAD

**Issue by qeuyee** [AppFlowy-IO/AppFlowy#4904] opened 2024-03-15 01:06 UTC
### Bug Description

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/31116292/3aeb2064-ec2b-4942-809a-4a5cdcb1e7b6)

### How to Reproduce

third-party sign-in

### Expected Behavior

missing field `icon` at line 1 column 540

### Operating System

win11

### AppFlowy Version(s)

0.5.2

**Comment by speed2exe** [comment] 2024-03-15 07:52
Hi, @qeuyee 

I am able to reproduce this on Win11.
I want to gather more information on this.
- Is this a new user?
- Do you have this because you migrated from registered account before 0.5.2?
- Does going back to 0.5.1 solves the problem?
- When you use the phone app, does it have the same issue?

**Comment by qeuyee** [comment] 2024-03-15 08:50
I have set up a private Appflowy Cloud and use my GitHub account to log in. However, I have encountered the following main issues:

1.Before the AppFlowy version 0.5.1, it could be used normally, but there were issues with data synchronization. The data could not be synchronized to the mobile app or to another computer where I logged in with the same account on AppFlowy.

2.After updating to version 0.5.1, it automatically logged me out during use. When trying to log in again with my GitHub account, an error occurred with the following error message: "error message: code: UserUnauthorized msg: sign in with oauth error -10003".

3.After updating to version 0.5.2, I still could not log in with my GitHub account. The error message was: "missing field icon at line 1 column 540".

**Comment by qeuyee** [comment] 2024-03-15 08:51
> Hi, @qeuyee
> 
> I am unable to reproduce this on Win11. I want to gather more information on this.
> 
> * Is this a new user?
> * Do you have this because you migrated from registered account before 0.5.2?
> * Does going back to 0.5.1 solves the problem?
> * When you use the phone app, does it have the same issue?

I have set up a private Appflowy Cloud and use my GitHub account to log in. However, I have encountered the following main issues:

1.Before the AppFlowy version 0.5.1, it could be used normally, but there were issues with data synchronization. The data could not be synchronized to the mobile app or to another computer where I logged in with the same account on AppFlowy.

2.After updating to version 0.5.1, it automatically logged me out during use. When trying to log in again with my GitHub account, an error occurred with the following error message: "error message: code: UserUnauthorized msg: sign in with oauth error -10003".

3.After updating to version 0.5.2, I still could not log in with my GitHub account. The error message was: "missing field icon at line 1 column 540".

**Comment by speed2exe** [comment] 2024-03-15 08:53
@qeuyee Are you self-hosting AppFlowy Cloud?

**Comment by qeuyee** [comment] 2024-03-15 08:59
> @qeuyee Are you self-hosting AppFlowy Cloud?

yes

**Comment by speed2exe** [comment] 2024-03-15 09:01
@qeuyee You might need to update the appflowy-cloud images. you can do `docker compose pulll`, then 'docker compose up -d` to use the new images.

**Comment by qeuyee** [comment] 2024-03-15 09:03
thanks

> @qeuyee You might need to update the appflowy-cloud images. you can do `docker compose pull`, then `docker compose up -d` to use the new images.

Thanks，After the update, are the data that I previously synchronized still there?

**Comment by qeuyee** [comment] 2024-03-15 09:10
> @qeuyee You might need to update the appflowy-cloud images. you can do `docker compose pull`, then `docker compose up -d` to use the new images.

The problem has been resolved.

**Comment by qeuyee** [comment] 2024-03-15 09:17
> @qeuyee You might need to update the appflowy-cloud images. you can do `docker compose pull`, then `docker compose up -d` to use the new images.

Does the AppFlowy Cloud need to be synchronously updated every time the AppFlowy version is updated?

**Comment by speed2exe** [comment] 2024-03-15 09:25
@qeuyee 
This does not happen for every update, this happened because the schema changed in the desktop app but the server still retains the old schema.
As much as possible, we will also keep them backward compatible.
Thanks for raising this issue, we will try to maintain backward compatibility with server.

**Comment by DevaanshPathak** [comment] 2024-03-22 03:17
@annieappflowy please close this issue as it has been resolved

**Closed** 2024-03-22 03:44 UTC
Labels: bug, cloud
