### ISSUE TITLE
[Bug] Kanban board sometimes doesn't let move individual tasks

### ISSUE THREAD

**Issue by L0Lock** [AppFlowy-IO/AppFlowy#5786] opened 2024-07-22 17:46 UTC
### Bug Description

After creating one or a few tasks in a Kanban board, sometimes when I try to drag a task to move it across collumns, it moves the whole column instead of the individual task. Switching to another page and back seems to fix the issue, until it happens again.

### How to Reproduce

Make new tasks and try to move them. It doesn't seem to bug systematically, but frequently enough for me.

![2024-07-22_13h44_AppFlowy_1789](https://github.com/user-attachments/assets/43d485bd-1466-457a-8f0d-188ca168a983)

### Expected Behavior

Dragging tasks should always move the task and not the whole collumn.

### Operating System

Windows 11 Pro Version	10.0.22631 Build 22631

### AppFlowy Version(s)

0.6.4 But I had the issue on a previous version (IDK which one, I updated hoping the issue would be solved)

**Comment by SophiaOquias** [comment] 2024-09-03 10:11
I get the same issue as well. This always happens when I create new cards on the board. 

Operating on: Pop!_OS jammy 22.04 x86_64 

The problem also persists on the flatpak version and .deb version of the app.

**Comment by LinuxLowell** [comment] 2024-09-04 12:53
I think this is a duplicate of [Issue 5525](https://github.com/AppFlowy-IO/AppFlowy/issues/5525).

**Comment by richardshiue** [comment] 2024-09-10 13:46
Closing as completed in the newest release for now, feel free to reopen and let me know if you still see this behavior

**Closed by richardshiue** 2024-09-10 13:46 UTC
Labels: bug, kanban board, Q3 24
