### ISSUE TITLE
[Bug] Slash command (/) not working with German or Spanish keyboard layout

### ISSUE THREAD

**Issue by rlndkhlr** [AppFlowy-IO/AppFlowy#2070] opened 2023-03-21 13:44 UTC
### Bug Description

The command menu (slash command) is not displayed / cannot be used when typing the `/` trigger. This happens when the computer's keyboard layout is set to German.

Discovered by testing different keyboard layouts:
German: ❌ (`/` on Shift+7)
English US: ✅ (`/` on first key left of right Shift key)
English UK: ✅ (`/` on first key left of right Shift key)
French: ✅ (`/` on second key left of right Shift key)
Spanish: ❌ (`/` on Shift+7)

Copy + Paste the `/` command does not work on either layout.

### How to Reproduce

Independent from connected hardware, changing the OS keyboard layout to German/Spanish and type in a `/` (Shift+7).

### Expected Behavior

Pressing Shift+7 on a German/Spanish keyboard to write a `/` and have the command menu appear.

### Operating System

macOS Ventura 13.1

### AppFlowy Version(s)

Version 0.1.0 (1) & Version 0.1.1 (1)

**Comment by Xazin** [comment] 2023-03-21 13:54
Duplicate of https://github.com/AppFlowy-IO/AppFlowy/issues/1876

**Comment by rlndkhlr** [comment] 2023-03-21 13:58
> Duplicate of #1876

Apologies, did not find a bug report using different keywords but glad that it is already on the radar. :)

**Comment by a-wallen** [comment] 2023-03-23 01:10
Closing as this is a duplicate of https://github.com/AppFlowy-IO/AppFlowy/issues/1876. Thank you @Xazin :)

**Closed by a-wallen** 2023-03-23 01:10 UTC
