### ISSUE TITLE
[Bug] error report

### ISSUE THREAD

**Issue by taylormao** [AppFlowy-IO/AppFlowy#2163] opened 2023-04-01 03:49 UTC
### Bug Description

"I downloaded an installation package, a compressed file. Firstly, I extracted it to the tools directory under my D drive, and then I clicked on appflowy.exe, which resulted in a white window appearing. After about 20-30 seconds, this window closes by itself."

### How to Reproduce

I do nothing but unzip the` AppFlowy_0.1.2_windows-x86_64.zip` to D:/tools ,and click the
appflowy.exe.

### Expected Behavior

[Report -.txt](https://github.com/AppFlowy-IO/AppFlowy/files/11128390/Report.-.txt)
this is error report 

### Operating System

Windows 10 LTSC Version 21H2

### AppFlowy Version(s)

AppFlowy_0.1.2

### Screenshots

![](https://f002.backblazeb2.com/file/images-taylor-pc/ShareX/2023/03/AppFlowy_jLNTRQQnbq.png)

**Comment by a-wallen** [comment] 2023-04-04 00:38
@taylormao could we close this issue as a duplicate of https://github.com/AppFlowy-IO/AppFlowy/issues/2152? The issues are almost the same, but https://github.com/AppFlowy-IO/AppFlowy/issues/2152 has logs attached I think that one should be better,

**Comment by taylormao** [comment] 2023-04-04 01:00
> @taylormao could we close this issue as a duplicate of #2152? The issues are almost the same, but #2152 has logs attached I think that one should be better,

yes, these two questions are indeed caused by the same reason. They can be merged together.

**Comment by a-wallen** [comment] 2023-04-04 02:24
Thank you, closing as duplicate of https://github.com/AppFlowy-IO/AppFlowy/issues/2152.

**Closed by a-wallen** 2023-04-04 02:24 UTC
