### ISSUE TITLE
[Bug] No backslash to ignore markdown in AppFlowy

### ISSUE THREAD

**Issue by MayurSMahajan** [AppFlowy-IO/AppFlowy#3628] opened 2023-10-05 15:50 UTC
### Bug Description

Appflowy Editor is a markdown editor, we use commonly use markdown shortcuts like double underscores to make text italic, etc.
But right now there is no way to ignore the markdown syntax.
So if a user wants to surround something with two underscores and not make it italic and display it like:  \_sometext\_. 
Then it is not possible.

Other markdown editors support the use of the backslash key (\) to ignore the markdown syntax.

### How to Reproduce

1. Open AppFlowy
2. Try typing something and wrap it with any markdown character preceded with backslash.
3. Observe that the markdown is still not ignored.

### Expected Behavior

Users should be able to use the backslash key to ignore the markdown syntax if they want.

### Operating System

Windows 11

### AppFlowy Version(s)

0.3.4

### Screenshots

https://github.com/AppFlowy-IO/AppFlowy/assets/47064215/ae7f0b8d-2394-45f4-9ce5-f162447a0c7b

### Additional Context

This happens with Styling Markdown syntax
https://docs.appflowy.io/docs/appflowy/product/markdown#styling-text

Originally noticed in #3624

**Comment by PalaniappanC** [comment] 2023-10-06 10:31
Hi @MayurSMahajan I would like to work on this issue. Please assign it to me

**Comment by MayurSMahajan** [comment] 2023-10-06 10:33
Assigned have fun!

**Comment by PalaniappanC** [comment] 2023-10-13 02:47
Update: I have started working on this. Will provide another update by weekend

**Comment by tmaiaroto** [comment] 2023-10-27 15:58
Can markdown parsing be something disabled via config setting? So if off and we want markdown, typing `/` to bring up the menu to choose a "markdown" option (like code block, image, table, etc. already are today) would switch that block to markdown?

I like the shortcut to avoid having markdown parsed, but I would prefer to disable markdown completely by default and choose when to use it. Most times I just want a very simple text editor.

Also ok with the same backtick shortcut GitHub has, but the problem is you can't edit text in there. In other words, you need to type everything at once. If you go back in between the backticks, you're adding normal text.

The second issue is that markdown is parsed while you are in the middle of the backtick.

So you type ` and then go to type a word with two underscores before you close that backtick and things end up italic inside the red code.

Ultimately the markdown parsing makes it impossible to do anything other than use a code block if you have multiple underscores in a line. It's a way big issue actually. I know I just rattled off  what are a few different issues, sorry.

**Comment by MayurSMahajan** [comment] 2023-10-27 16:32
Hey @tmaiaroto ! Thanks for your feedback. I will create a separate issue for your feature request. A way to disable and enable markdown feature.

**Comment by Xazin** [comment] 2023-10-29 19:16
Note for implementation: Use RegExp and use a negative lookbehind for `\`.

**Comment by Xazin** [comment] 2023-10-29 19:16
@PalaniappanC Are you still working on this?

**Comment by PalaniappanC** [comment] 2023-10-30 02:44
Yes @Xazin. Even if not part of hacktoberfest I would like to continue

**Comment by PalaniappanC** [comment] 2023-10-30 02:44
I am not able to debug the backend code which has the logic for mark down

**Comment by Xazin** [comment] 2023-10-30 07:41
> I am not able to debug the backend code which has the logic for mark down

All of the markdown parsing happens on the front end, mostly powered by character shortcuts.

There should be no backend work involved in this feature.

**Comment by Xazin** [comment] 2023-12-10 20:25
> I tried going through the front end but was unable to find the feature. Can someone link the file?

Hey Devaansh, this issue is not easy to complete, hence the "good first issue for **experienced devs**".

There are some implications with the way we implement character shortcuts, and thus this had to be completed in the AppFlowy Editor repository.

One supposed solution would be to implement a generic check for any character shortcut that does transformations (and this would require the character shortcut to have a flag that is a promise that they do a transformation), and then if they have this flag, don't run the character shortcut if it is canceled by the backslash.

**Closed** 2024-01-17 00:43 UTC
Labels: new feature, editor, 2024
