### ISSUE TITLE
[Bug] Issues with the dark theme

### ISSUE THREAD

**Issue by Kertrix** [AppFlowy-IO/AppFlowy#429] opened 2022-04-05 19:28 UTC
**Describe the bug**
Some elements are invisible when the dark theme is enabled.

**To Reproduce**
1. Use the dark theme

**Screenshots**
![image](https://user-images.githubusercontent.com/75695086/161833883-040fd09d-b477-4856-9425-1b684c09fabe.png)
The plus sign is barely visible as it is a dark color (at first glance I didn't see it)
![image](https://user-images.githubusercontent.com/75695086/161834176-30eab2d1-098e-42d3-bdac-f39bb95f6677.png)
When the highlighting is a light color, the text is invisible as it is white.

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.10
 - Browser N/A
 - Version 1.0.0.1

**Additional context**
 - Environment [e.g. flutter doctor -v or rustup show]
None

**Comment by leochras** [comment] 2022-04-13 20:39
I also think the UI elements should have a lighter color or more contrast

**Comment by apomalyn** [comment] 2022-05-16 13:52
This is a duplicate of #433. Could you close this and if missing something add a comment on #433 😄 Thank you!

**Closed** 2022-05-16 13:54 UTC
