### ISSUE TITLE
[FR] Server sync

### ISSUE THREAD

**Issue by maticrivo** [AppFlowy-IO/AppFlowy#17] opened 2021-11-16 12:08 UTC
**1~3 main use cases of the proposed feature**
Are there plans to have a server one can self-host for syncing files between multiple devices (computers, cellphones, tablets...)?
Alternatively it can be a good option to let the users decide where to store the sqlite database (dropbox, icloud, google drive, etc...)

**what types of users can benefit from using your proposed feature**
Every user that uses more then 1 device

**Additional context**
Nothing to add besides this is a great project and it looks great!

**Comment by markosole** [comment] 2021-11-16 12:35
You may have few options: 
1. Store on Google Drive and share between devices
2. Create Server API with realtime DB and storage on AWS S3 bucket. 

Depends of complexity and requirements.

**Comment by annieappflowy** [comment] 2021-11-17 02:21
> **1~3 main use cases of the proposed feature** Are there plans to have a server one can self-host for syncing files between multiple devices (computers, cellphones, tablets...)? Alternatively it can be a good option to let the users decide where to store the sqlite database (dropbox, icloud, google drive, etc...)
> 
> **what types of users can benefit from using your proposed feature** Every user that uses more then 1 device
> 
> **Additional context** Nothing to add besides this is a great project and it looks great!

Thanks a lot for your inputs. End-to-end encryption sync is sitting on our roadmap. This is something that users with more than one device would need. Your alternative plan sounds promising. I'm wondering where you'd like to store? Is there any data security concern?

Annie

**Comment by emengweb** [comment] 2021-11-18 00:02
self-host and share with peoole like website :D

**Comment by bgervan** [comment] 2021-11-21 09:05
I am working on a flutter + hive (can be other DB if it allow to define base class) + crdt + django channels backend package. 
Would it be something Appflowy is interested to use? If they implement offline working with that, my package can sync with django backend real time. For one user with multiple device it already works (need to clean the code etc). For multiple user I need to improve it. Of course the django app can be self hosted

**Comment by jjeejj** [comment] 2023-02-17 15:34
Minio ， S3  Or other object storage

**Comment by remram44** [comment] 2023-02-21 16:25
Duplicate of https://github.com/AppFlowy-IO/AppFlowy/discussions/540

**Comment by annieappflowy** [comment] 2023-02-27 06:40
https://github.com/AppFlowy-IO/AppFlowy/issues/602

**Comment by iBobik** [comment] 2023-03-27 12:08
Some ideas, what do you think?

- Would be nice (and cheap) to symmetrically encrypt per file and allow user to share by links.

- There could be multiple kind of keys - owner, edit and view. Owner can manage them, generate multiple links with different keys etc. Owner keys could maybe be asymmetric public keys, edit key just random string.

- By default owner file keys are stored in user account and view keys in parent folder (in a link to the child file?). User can get share link like: https://share.appflowy.io/FILE_ID#view=FILE_KEY&edit=EDIT_KEY.

- On the server there will be dump CDN with SPA. It will get file by its ID from S3-like storage, decrypt by view key in hash and render. So viewing files will be cheap.

- For saving and colaboration there will have to be some backend which will check edit and owner keys. Also it can enforce billing.

- For sake of freedom there could be not only super simple to use official paid cloud, but also option to store plain markdown files anywhere (local, Dropbox, Drive, iCloud, …).

**Comment by iBobik** [comment] 2023-03-28 15:16
Tell me about some specific alternative and I will compare it 😉

But generally usual solutions does not care about privacy and want to motivate more people to create accounts or at least generate leads (collect contacts).

Also my proposal is cheaper to operate. (At least view only sharing.)

**Comment by iBobik** [comment] 2023-03-28 15:18
Also that view only sharing could be very simple to implement.

**Comment by xezzon** [comment] 2023-07-07 06:24
Will WebDAV be supported?

**Comment by almereyda** [comment] 2023-11-24 02:54
Is there a chance that this is now implemented with [AppFlowy-IO/AppFlowy-Cloud](https://github.com/AppFlowy-IO/AppFlowy-Cloud)?

**Comment by annieappflowy** [comment] 2023-12-24 19:11
We now support self-hosting AppFlowy: https://docs.appflowy.io/docs/guides/appflowy/self-hosting-appflowy

**Closed by annieappflowy** 2023-12-24 19:11 UTC
Labels: new feature
