### ISSUE TITLE
[Bug] Copy paste a link containing "#" doesn't work

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#1871] opened 2023-02-18 12:14 UTC
### Bug Description

I'm trying to copy paste https://github.com/AppFlowy-IO/AppFlowy/issues/1867#issuecomment-1433204980 into the document
It only recoginizes the part before "#" as a link

### How to Reproduce

<img width="526" alt="image" src="https://user-images.githubusercontent.com/12026239/219865147-6b6020de-505b-4c73-868b-88ebd269bed0.png">

### Expected Behavior

Paste it as a link, and I can also open the link

### Operating System

Windows 10

### AppFlowy Version(s)

v0.1.0

**Comment by AFZL210** [comment] 2023-03-07 12:31
I think the problem might be caused by the input field that stores pasted data,
can i work on this?

**Comment by LucasXu0** [comment] 2023-03-08 01:56
Hey, @AFZL210. Sure. I assigned it to you.

**Comment by Xazin** [comment] 2023-03-26 01:30
Didn't see someone was assigned to this issue, the problem was quite simple, the regex when handling single-line plain rich text pasting in the editor, didn't recognize # in URLs due to the regex.

**Closed** 2023-03-27 04:47 UTC
Labels: bug, editor
