### ISSUE TITLE
[Bug] AppFlowy magic link does not work with ProtonMail

### ISSUE THREAD

**Issue by dsailly** [AppFlowy-IO/AppFlowy#5710] opened 2024-07-09 15:51 UTC
### Bug Description

Hello,

I've been trying for some time to create an AppFlowy account with my ProtonMail account (with alias and with the classic address). The magic link is never sent to my email address (not in spam either).

However, I tested it with an old Gmail account and it worked straight away

### How to Reproduce

Use Proton mail address for sending a magic link

### Expected Behavior

I want to use my protonmail account to create an AppFlowy account

### Operating System

Pop_OS ! (Linux)

### AppFlowy Version(s)

0.6.3

### Screenshots

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/167969134/d728d8fa-4a2b-4ffb-90e9-69e8c880aa6d)

### Additional Context

I tested with the Flatpak and .deb version

Thanks you !

**Comment by xkevinx** [comment] 2024-07-09 16:34
Just had the same issue! I couldn't receive any email until I tried with an old gmail account.

**Comment by speed2exe** [comment] 2024-07-10 03:49
@dsailly I have signed up for proton mail and tried to login with magic link, unable to reproduce this issue. i am using the domain `protonmail.com` is this also the case for you?

**Comment by speed2exe** [comment] 2024-07-10 14:51
@dsailly have you tried to changing the mail filtering settings in the protonmail? https://account.proton.me/u/0/mail/filters

**Comment by speed2exe** [comment] 2024-07-12 02:46
@dsailly are you using aliases? https://proton.me/support/addresses-and-aliases

**Comment by speed2exe** [comment] 2024-07-15 09:31
@dsailly have you set up email and phone number recovery for your email?

**Comment by annieappflowy** [comment] 2024-10-01 13:16
Closing it as we have not received the response since July

**Closed by annieappflowy** 2024-10-01 13:16 UTC
