### ISSUE TITLE
[Bug] Workspace failed to load

### ISSUE THREAD

**Issue by dmitriigolovchenko** [AppFlowy-IO/AppFlowy#3758] opened 2023-10-23 09:03 UTC
### Bug Description

After reboot appflowy I see "Something went wrong. Failed to load workspace. Try to close any open instance of appflowy" - it doesn`t work. 

### How to Reproduce

May be problem with 3 opened tabs, before i close app. Start screen now looks https://disk.yandex.ru/i/JUv8aDg_olBqOw

### Expected Behavior

Startup screen of appflowy

### Operating System

windows

### AppFlowy Version(s)

0.3.6

### Screenshots

![2023-10-23_12-02-32](https://github.com/AppFlowy-IO/AppFlowy/assets/101408961/743f7d54-97c5-4197-8e93-a80de491199d)

**Comment by Xazin** [comment] 2023-10-23 09:07
Hey @dmitriigolovchenko, this screen shows when the workspace fails to load, can you please try the following:

- Make sure only one AppFlowy application is open at a time (close all open AppFlowy applications and open AppFlowy again)
- Backup and delete, or move, your existing AppFlowy Data folder.

**Comment by Xazin** [comment] 2023-10-25 17:39
Just checking in @dmitriigolovchenko, did you solve your issue, or is still persisting?

**Comment by smit-io** [comment] 2023-10-29 17:57
I have the same issue. If I set up a new data folder, does that mean I have to start from scratch? All my data is gone?

**Comment by Xazin** [comment] 2023-10-29 19:18
> I have the same issue. If I set up a new data folder, does that mean I have to start from scratch? All my data is gone?

The issue is, it's extremely hard for us to understand what is causing the workspace to fail to load, since we would need a corrupt workspace to debug it.

If you are sure you do not have any open instance of AppFlowy when opening the application, and you get this error, then most likely some part of the workspace is corrupt or missing something.

**Comment by smit-io** [comment] 2023-10-29 20:20
I only have one instance of the app running and now I have lost about 8 hours of my work due to this. Was really looking forward to using appflowy but I think I will have to wait for a bit.

**Comment by dmitriigolovchenko** [comment] 2023-10-30 05:13
If it helps: my workspace in drive, that integrate to windows explorer

**Comment by annieappflowy** [comment] 2023-10-31 05:05
Hi @smit-io , your data won't be gone if you have not deleted the data folder. Please contact me in the [Discord](https://discord.gg/9Q2xaN37tV) server. We'll help.

**Comment by annieappflowy** [comment] 2023-10-31 05:08
> > I have the same issue. If I set up a new data folder, does that mean I have to start from scratch? All my data is gone?
> 
> The issue is, it's extremely hard for us to understand what is causing the workspace to fail to load, since we would need a corrupt workspace to debug it.
> 
> If you are sure you do not have any open instance of AppFlowy when opening the application, and you get this error, then most likely some part of the workspace is corrupt or missing something.
> 
> Yes, if you backup the data folder or move it, then the application would start anew since it would fail to find an existing data folder to read from.

To clarify, if you move the data folder to a new location, you can still open it by clicking on "Change" and point to the new location.
<img width="598" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/8a5bd0be-b2ef-4cbf-964f-79c9978b53fb">

**Comment by annieappflowy** [comment] 2023-10-31 05:09
> I only have one instance of the app running and now I have lost about 8 hours of my work due to this. Was really looking forward to using appflowy but I think I will have to wait for a bit.



> I have the same issue. If I set up a new data folder, does that mean I have to start from scratch? All my data is gone?

No it's not gone. You just have to point the app to the right folder.

**Comment by smit-io** [comment] 2023-11-06 00:39
> Hi @smit-io , your data won't be gone if you have not deleted the data folder. Please contact me in the [Discord](https://discord.gg/9Q2xaN37tV) server. We'll help.

I am pointing it to the right folder but it still shows that error.

**Comment by annieappflowy** [comment] 2023-11-06 03:27
You should come to the Discord server, @smit-io , so I can guide you to resolve it.

**Comment by annieappflowy** [comment] 2023-11-11 03:23
Some info a bit misleading on this thread. Closing it to avoid further confusion. Please come to the Disocrd server for help.

**Comment by badrc** [comment] 2023-11-17 23:21
same issue here
after hours writing and organizing my docs
appflowy can't open anymore
it starts fine when I start with an empty folder
but it crashes when I update the data directeory in the parameters

config : Windows 11 ( and data stored in a Google Drive)

**Comment by annieappflowy** [comment] 2023-11-18 05:11
The issue is from putting it into gDrive.
Could you try to move the folder put of your gDrive and try to open it with AppFlowy?
It should be working again
Let me know how it goes

**Comment by annieappflowy** [comment] 2023-11-18 05:15
> same issue here
> after hours writing and organizing my docs
> appflowy can't open anymore
> it starts fine when I start with an empty folder
> but it crashes when I update the data directeory in the parameters
> 
> config : Windows 11 ( and data stored in a Google Drive)

Can you share the latest log info?
It's located in the data folder

**Comment by appflowy** [comment] 2023-11-18 05:26
@badrc @dmitriigolovchenko, I'm sorry for any inconvenience caused. To help resolve the issue, could you please send me the logs located in the data folder? These logs are crucial for diagnosing the problem. Additionally, if you have any questions or need further assistance, feel free to reach out to me on Discord.

**Closed** 2023-12-21 18:23 UTC
