### ISSUE TITLE
[Bug] Can't change theme

### ISSUE THREAD

**Issue by PawnOfNord** [AppFlowy-IO/AppFlowy#4656] opened 2024-02-15 07:12 UTC
### Bug Description

https://github.com/AppFlowy-IO/AppFlowy/assets/156477687/370cdc0a-b603-436c-8a3b-8c4bf5935129

### How to Reproduce

Change theme

### Expected Behavior

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/156477687/e9167247-b3cb-4855-a366-11d235eb8d02)

### Operating System

MacOS Sonoma 14.3

### AppFlowy Version(s)

0.4.9

**Comment by LucasXu0** [comment] 2024-02-20 15:19
@PawnOfNord Any reproducible steps? I'm using macOS Sonoma 14.1 and couldn't reproduce it.

**Comment by PawnOfNord** [comment] 2024-02-23 10:17
All i did is just open settings and clicked "Default" to change theme

**Comment by PawnOfNord** [comment] 2024-02-23 10:18
All i did is just open settings and clicked "Default" to change theme

**Comment by annieappflowy** [comment] 2024-04-02 10:03
@PawnOfNord , are you still having this issue with the latest release? 
Since we cannot reproduce it on our macOS devices, closing it for now. Feel free to reopen it

**Closed by annieappflowy** 2024-04-02 10:03 UTC

**Comment by PawnOfNord** [comment] 2024-04-02 10:08
@annieappflowy Yes, I still have this issue. Maybe the thing is that I'm using not MacBook but Mac Mini?
