### ISSUE TITLE
[FR] Context menu launched when right clicking list item

### ISSUE THREAD

**Issue by TDuffinNTU** [AppFlowy-IO/AppFlowy#3694] opened 2023-10-13 13:53 UTC
### Description

Right now, you can only open the context menu for a document's list item by clicking the 2 dots beside its title: 
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/43959652/75020068-d192-4cb0-b688-8e249174f877)

This is quite difficult to reach on desktop as the target is small, and certain displays can scale it even smaller.

My proposed solution is to make the entire list item detect right click events (and possibly long taps for touch screens/mobile) so that the target is larger. This also brings the UX of list items closer to most others that I've seen in the wild.

### Impact

This will improve accessibility by making the click target for the context menu much easier to reach, and improve the speed of navigating and using the interface.

### Additional Context

This can coexist with the existing UX of the context menu being triggered by a left click on the dots imo. This is something I've also seen in, for example, atlassian confluence. The dots give a good "click me to see more" hint while the right click functionality makes that newly-discovered feature easy to access.

**Comment by Xazin** [comment] 2023-10-13 14:54
Duplicate of https://github.com/AppFlowy-IO/AppFlowy/issues/3135

**Closed by Xazin** 2023-10-13 14:54 UTC
