### ISSUE TITLE
[FR] Creation of link to a page

### ISSUE THREAD

**Issue by n0yal** [AppFlowy-IO/AppFlowy#6578] opened 2024-10-17 16:50 UTC
### Description

Currently when a link to a y page is created in x page if the y file does not exist then the link is not formed. Just a suggestion that it should create a link in x page and when clicked should create a new file just like in notion . 

### Impact

Practically every users when creating the link . Now i have to create a new file whenever i have to create a link and then return to the page i was typing to create a link and create.

**Comment by Xazin** [comment] 2024-10-18 13:21
Is this a duplicate of one of these?

#5692 #5417 #5134

**Comment by n0yal** [comment] 2024-10-19 08:26
> Is this a duplicate of one of these?
> 
> #5692 #5417 #5134

I think it is the same hence closing this request.

**Closed** 2024-10-19 08:27 UTC
