### ISSUE TITLE
[FR] Sync data across devices

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#713] opened 2022-07-25 12:14 UTC

**Comment by jjeejj** [comment] 2023-02-17 15:42
Hello, a year has passed. Is there any progress?

**Comment by remram44** [comment] 2023-02-21 16:26
Duplicate of Duplicate of https://github.com/AppFlowy-IO/AppFlowy/discussions/540, #602, #17, #537

**Closed** 2023-12-24 18:28 UTC
