### ISSUE TITLE
[Bug] The current version does not support this block

### ISSUE THREAD

**Issue by Joso997** [AppFlowy-IO/AppFlowy#4483] opened 2024-01-24 14:25 UTC
### Bug Description

Like what is happening at this point, I am using the same software version on two computers and when I load from the other PC I get this: "The current version does not support this block".

We will have to stop using this software because on multiple occasions we have lost hours of work

### How to Reproduce

I don't know, logging in from a different PC

### Expected Behavior

To not get "The current version does not support this block"

### Operating System

Windows 11

### AppFlowy Version(s)

0.4.3

### Additional Context

Since I have our content in json content when I click on "The current version does not support this block" can I somehow save my work?

**Comment by LucasXu0** [comment] 2024-01-24 14:50
@Joso997 Could you share which block you used? The data won't be lost. this problem may occur if some data validation fails.

**Comment by Joso997** [comment] 2024-01-24 15:05
It is fine now, for some time we were not able to even log in. But eventually it enabled us to log in and file was correctly shown.

Will there eventually be support for multiuser, because we are currently sharing the same user over cloud beta feature

**Comment by Joso997** [comment] 2024-01-24 15:07
Or at least for a way for us to make a backup on regular intervals. Back when we had local only, we made online cloud experience using github commits

**Comment by Joso997** [comment] 2024-01-24 15:09
> @Joso997 Could you share which block you used? The data won't be lost. this problem may occur if some data validation fails.

Here is one of the blocks:

{"type":"table","children":[{"type":"table/cell","children":[{"type":"paragraph","data":{"delta":[{"attributes":{"bold":true},"insert":"Component Type"}],"align":"center"}}],"data":{"rowPosition":0,"colPosition":0,"width":109.0,"height":64.0}},{"type":"table/cell","children":[{"type":"paragraph","data":{"delta":[{"insert":"InputGroupComponent"}]}}],"data":{"rowPosition":1,"colPosition":0,"width":109.0,"height":64.0}},{"type":"table/cell","children":[{"type":"paragraph","data":{"delta":[]}}],"data":{"width":109.0,"rowPosition":2,"colPosition":0,"height":64.0}},{"type":"table/cell","children":[{"type":"paragraph","data":{"delta":[]}}],"data":{"rowPosition":3,"height":40.0,"width":109.0,"colPosition":0}},{"type":"table/cell","children":[{"type":"paragraph","data":{"delta":[{"attributes":{"bold":true},"insert":"Object Type"}],"align":"center"}}],"data":{"colPosition":1,"rowPosition":0,"height":64.0,"width":102.0}},{"type":"table/cell","children":[{"type":"paragraph","data":{"delta":[{"insert":"InputGroup"}]}}],"data":{"rowPosition":1,"width":102.0,"colPosition":1,"height":64.0}},{"type":"table/cell","children":[{"type":"paragraph","data":{"delta":[{"insert":"Label"}]}}],"data":{"rowPosition":2,"width":102.0,"colPosition":1,"height":64.0}},{"type":"table/cell","children":[{"type":"paragraph","data":{"delta":[{"insert":"Field"}]}}],"data":{"rowPosition":3,"width":102.0,"colPosition":1,"height":40.0}},{"type":"table/cell","children":[{"type":"paragraph","data":{"delta":[{"attributes":{"bold":true},"insert":"Label"}],"align":"center"}}],"data":{"colPosition":2,"height":64.0,"width":186.0,"rowPosition":0}},{"type":"table/cell","children":[{"type":"paragraph","data":{"align":"center","delta":[{"insert":"/"}]}}],"data":{"rowPosition":1,"colPosition":2,"height":64.0,"width":186.0}},{"type":"table/cell","children":[{"type":"paragraph","data":{"delta":[{"insert":"_t(CyberLang::name), 'label'"}]}}],"data":{"width":186.0,"height":64.0,"colPosition":2,"rowPosition":2}},{"type":"table/cell","children":[{"type":"paragraph","data":{"delta":[{"insert":"''"}]}}],"data":{"width":186.0,"colPosition":2,"rowPosition":3,"height":40.0}},{"type":"table/cell","children":[{"type":"paragraph","data":{"delta":[]}}],"data":{"colPosition":3,"height":64.0,"width":150.0,"rowPosition":0}},{"type":"table/cell","children":[{"type":"paragraph","data":{"delta":[{"insert":"CyberTags::name"}]}}],"data":{"width":150.0,"colPosition":3,"rowPosition":1,"height":64.0}},{"type":"table/cell","children":[{"type":"paragraph","data":{"align":"center","delta":[{"insert":"/"}]}}],"data":{"colPosition":3,"rowPosition":2,"height":64.0,"width":150.0}},{"type":"table/cell","children":[{"type":"paragraph","data":{"delta":[{"insert":"/"}],"align":"center"}}],"data":{"width":150.0,"colPosition":3,"height":40.0,"rowPosition":3}},{"type":"table/cell","children":[{"type":"paragraph","data":{"delta":[]}}],"data":{"colPosition":4,"height":64.0,"rowPosition":0,"width":40.0}},{"type":"table/cell","children":[{"type":"paragraph","data":{"delta":[{"insert":"$id"}]}}],"data":{"rowPosition":1,"width":40.0,"colPosition":4,"height":64.0}},{"type":"table/cell","children":[{"type":"paragraph","data":{"delta":[{"insert":"/"}],"align":"center"}}],"data":{"rowPosition":2,"colPosition":4,"height":64.0,"width":40.0}},{"type":"table/cell","children":[{"type":"paragraph","data":{"delta":[{"insert":"$id"}]}}],"data":{"rowPosition":3,"colPosition":4,"width":40.0,"height":40.0}},{"type":"table/cell","children":[{"type":"paragraph","data":{"delta":[]}}],"data":{"height":64.0,"width":144.0,"rowPosition":0,"colPosition":5}},{"type":"table/cell","children":[{"type":"paragraph","data":{"delta":[{"insert":"/"}],"align":"center"}}],"data":{"rowPosition":1,"height":64.0,"width":144.0,"colPosition":5}},{"type":"table/cell","children":[{"type":"paragraph","data":{"delta":[{"insert":"input-group-text"}]}}],"data":{"rowPosition":2,"width":144.0,"height":64.0,"colPosition":5}},{"type":"table/cell","children":[{"type":"paragraph","data":{"delta":[{"insert":"/"}],"align":"center"}}],"data":{"colPosition":5,"rowPosition":3,"width":144.0,"height":40.0}},{"type":"table/cell","children":[{"type":"paragraph","data":{"delta":[]}}]},{"type":"table/cell","children":[{"type":"paragraph","data":{"delta":[{"insert":"Optional"}]}}]},{"type":"table/cell","children":[{"type":"paragraph","data":{"align":"center","delta":[{"insert":"/"}]}}]},{"type":"table/cell","children":[{"type":"paragraph","data":{"delta":[{"insert":"/"}],"align":"center"}}]},{"type":"table/cell","children":[{"type":"paragraph","data":{"align":"center","delta":[{"attributes":{"bold":true},"insert":"BelongsTo"}]}}],"data":{"width":150.0,"colPosition":7,"rowPosition":0,"height":64.0}},{"type":"table/cell","data":{"height":64.0,"colPosition":7,"width":150.0,"rowPosition":1}},{"type":"table/cell","children":[{"type":"paragraph","data":{"delta":[{"insert":"CyberTags::name"}]}}],"data":{"width":150.0,"rowPosition":2,"height":64.0,"colPosition":7}},{"type":"table/cell","children":[{"type":"paragraph","data":{"delta":[{"insert":"CyberTags::name"}]}}],"data":{"rowPosition":3,"width":150.0,"colPosition":7,"height":40.0}},{"type":"table/cell","children":[{"type":"paragraph","data":{"delta":[]}}],"data":{"height":64.0,"colPosition":8,"rowPosition":0,"width":348.0}},{"type":"table/cell","children":[{"type":"paragraph","data":{"delta":[{"insert":"CyberUtility::getValidateErrorMessage(null, _t(CyberLang::name), ['required'])"}]}}],"data":{"colPosition":8,"width":348.0,"height":64.0,"rowPosition":1}},{"type":"table/cell","children":[{"type":"paragraph","data":{"delta":[{"insert":"/"}],"align":"center"}}],"data":{"colPosition":8,"rowPosition":2,"width":348.0,"height":64.0}},{"type":"table/cell","children":[{"type":"paragraph","data":{"delta":[{"insert":"/"}],"align":"center"}}],"data":{"height":40.0,"rowPosition":3,"colPosition":8,"width":348.0}}]}

**Comment by annieappflowy** [comment] 2024-01-24 16:16
@Joso997 , you will always have a local copy with built in version history using cloud, so it's unlikely to completely lose your recent data unless the data is corrupted. Could you please reach out us on [Discord](https://discord.gg/9Q2xaN37tV) and share the log file with me? We'd like to debug and fix the issues you encountered.

**Comment by Joso997** [comment] 2024-01-25 15:41
Hi same bug again.
here is debug info:
computerName: DESKTOP-TOJLL8R
numberOfCores: 4
systemMemoryInMegabytes: 16384
userName: 10Administrator
majorVersion: 10
minorVersion: 0
buildNumber: 19045
platformId: 2
csdVersion: 
servicePackMajor: 0
servicePackMinor: 0
suitMask: 256
productType: 1
reserved: 0
buildLab: 19041.vb_release.191206-1406
buildLabEx: 19041.1.amd64fre.vb_release.191206-1406
digitalProductId: [4, 0, 0, 0, 0, 0, 0, 0, 152, 111, 94, 191, 175, 1, 0, 0, 227, 30, 181, 37, 175, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 152, 111, 94, 191, 0, 0, 0, 0, 48, 202, 180, 37, 175, 1, 0, 0, 49, 133, 210, 9, 175, 1, 0, 0, 219, 30, 181, 37, 175, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 49, 133, 210, 9, 0, 0, 0, 0, 160, 195, 180, 37, 175, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, 90, 149, 37, 175, 1, 0, 0, 107, 0, 0, 0, 66, 5, 36, 0, 4, 0, 0, 0, 0, 0, 0, 0, 96, 145, 76, 26, 175, 1, 0, 0, 0, 0, 0, 0, 66, 5, 33, 0, 5, 0, 0, 0, 0, 0, 0, 0, 80, 161, 152, 37, 175, 1, 0, 0, 107, 0, 0, 0, 66, 5, 8, 0, 6, 0, 0, 0]
displayVersion: 22H2
editionId: Professional
installDate: 2021-10-01 09:55:06.000
productId: 00330-80000-00000-AA369
productName: Windows 10 Pro
registeredOwner: 10Administrator
releaseId: 2009
deviceId: {735ABEEB-6A08-47D0-93CD-47C45EE98564}
Document: C:\Users\10Administrator\AppData\Roaming\io.appflowy\AppFlowy\data
<img width="412" alt="Screenshot_10" src="https://github.com/AppFlowy-IO/AppFlowy/assets/23720628/35ead106-f40c-4777-a406-58677661b96c">

**Comment by LucasXu0** [comment] 2024-01-26 13:54
@Joso997 I tried to reproduce the data you provided. Some of the required values are missing. Did this issue occur on the machine where you wrote the content or on the other machine where you synchronized the data?

**Comment by annieappflowy** [comment] 2024-04-02 03:23
@Joso997 , team collab up to 10 members will be included in the upcoming release (v0.5.4) and also the self-hosted solutions. Closing this issue for now as there hasn't been a response since Jan 26.

**Closed by annieappflowy** 2024-04-02 03:23 UTC
