### ISSUE TITLE
[Bug] Chinese input bugs

### ISSUE THREAD

**Issue by MadMrFox** [AppFlowy-IO/AppFlowy#2260] opened 2023-04-14 07:05 UTC
### Bug Description

1.The order of words will be reversed when typing Chinese in Document

2.letters（Pinyin，like English Phonetic Symbols） will be output when entering Chinese by using windows remote access

### How to Reproduce

Use Chinese input method during remote access

### Expected Behavior

Try to solve the Chinese input method disorder problem as first

### Operating System

windows10

### AppFlowy Version(s)

v0.1.2

### Screenshots

![2](https://user-images.githubusercontent.com/24291784/231968036-22728f49-7c99-47e7-a11a-3c71667e38d7.png)

**Comment by skydtrtzmr** [comment] 2023-05-13 14:50
still exists in v0.1.5

**Comment by annieappflowy** [comment] 2023-06-24 06:47
duplicate of https://github.com/AppFlowy-IO/AppFlowy/issues/1756

**Closed by annieappflowy** 2023-06-24 06:47 UTC
