### ISSUE TITLE
[Bug] Tooltip text visibility

### ISSUE THREAD

**Issue by shan-shaji** [AppFlowy-IO/AppFlowy#1706] opened 2023-01-14 09:02 UTC
### Bug Description

On dark mode in macOs on hover the Tooltip text is not readable.

### How to Reproduce

Hover over  + icon along with the getting started text.

### Expected Behavior

The text should be readable in dark mode also.

### Operating System

MacOS

### AppFlowy Version(s)

v0.0.9.1

### Screenshots

<img width="310" alt="Screenshot 2023-01-14 at 2 19 12 PM" src="https://user-images.githubusercontent.com/42430941/212464177-fde79d8c-871c-46c1-807d-190db9fecd95.png">

**Comment by richardshiue** [comment] 2023-01-16 05:30
Closing, duplicate of #1575

**Closed by richardshiue** 2023-01-16 05:30 UTC
