### ISSUE TITLE
[Bug] msg: got error code: 502 Bad Gateway, body: error code: 502

### ISSUE THREAD

**Issue by gorghino** [AppFlowy-IO/AppFlowy#5739] opened 2024-07-15 11:11 UTC
### Bug Description

I cannot open one of my page in my workspace.
After a long loading, it shows:

Error message:
```
msg: got error code: 502 Bad Gateway, body: error code: 502

```

I guess something bad is happening on the cloud side.

### How to Reproduce

- Log in into Appflowy 0.6.3 on Ubuntu 22.04
- Open one of the shared workspace's page
- Get the error

### Expected Behavior

It shall open and sync without any errors

### Operating System

linux

### AppFlowy Version(s)

0.6.3 (snap)

### Additional Context

Error message:
```
msg: got error code: 502 Bad Gateway, body: error code: 502

```

**Comment by realmaaran** [comment] 2024-07-15 11:51
![Screenshot from 2024-07-15 17-20-01](https://github.com/user-attachments/assets/ef95ef8b-c942-4caf-ab01-4be2a73ff74d)

the error

**Comment by speed2exe** [comment] 2024-07-16 02:22
@gorghino @realmaaran Thank you for reporting the issue. We have identified the root cause and it will be fixed soon.

**Closed** 2024-08-08 07:41 UTC
