### ISSUE TITLE
[Bug] Can't see/scroll all cards in a calendar

### ISSUE THREAD

**Issue by Upacesky-26** [AppFlowy-IO/AppFlowy#4915] opened 2024-03-15 09:27 UTC
### Bug Description

I created a new calendar with at least 2 cards in the same day but I can't click on the second one. i see a mini scroll bar, but it doesn't scroll enough for me to see the second element

### How to Reproduce

- create calendar
- add 2 events the same day
- try to scroll

### Expected Behavior

I should be able to see all elements which are the same day in the calendar view

### Operating System

Manjaro Linux - Gnome

### AppFlowy Version(s)

0.5.1 - Flatpak

### Screenshots

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/68832429/60226ca5-567c-49f8-a974-292e8be2557f)

**Comment by annieappflowy** [comment] 2024-09-30 09:25
Closing it as we're unable to reproduce this issue

**Closed by annieappflowy** 2024-09-30 09:25 UTC
Labels: calendar
