### ISSUE TITLE
[Bug] Text Not Visible On Highlighting in Darkmode

### ISSUE THREAD

**Issue by krupalitrivedi** [AppFlowy-IO/AppFlowy#929] opened 2022-08-29 16:12 UTC
**Describe the bug**
When text is highlighted in the dark mode the highlight becomes so bright that the text becomes difficult to be red.

**To Reproduce**
1. Go to `AppFlowy -> Change to dark mode`
2. Type some text
4. Select the text and `highlight`

**Expected behavior**
The text should be visible!

**Screenshots**
![image](https://user-images.githubusercontent.com/99717469/187245747-6f589e9f-3372-4ac5-8ed3-1358ce2b8ff6.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Version [v0.0.4]

**Comment by annieappflowy** [comment] 2022-08-30 05:35
https://github.com/AppFlowy-IO/AppFlowy/issues/336
this is a duplicate of #336 
Please keep an eye out for that issue. Thanks for reporting it!

**Closed by annieappflowy** 2022-08-30 05:35 UTC
