### ISSUE TITLE
[Bug] Can not move the caret when switch the keyboard input language

### ISSUE THREAD

**Issue by samdychen** [AppFlowy-IO/AppFlowy#3831] opened 2023-10-30 04:12 UTC
### Bug Description

Below is the way to reproduce the issue:
1.  Firstly use Chinese language, input some wording
2. Then switch to English, input some wording
3. Delete the english wording by “Back” key
4. you are going to figure out that you can only delete the English wording, and cannot move the Caret 

My environment:
- MacOS x86, 14.0
- AppFlowy version, 0.3.6 

### How to Reproduce

Below is the way to reproduce the issue:
1.  Firstly use Chinese language, input some wording
2. Then switch to English, input some wording
3. Delete the english wording by “Back” key
4. you are going to figure out that you can only delete the English wording, and cannot move the Caret 

### Expected Behavior

cannot move the Caret 

### Operating System

MacOS x86, 14.0

### AppFlowy Version(s)

0.3.6

**Comment by annieappflowy** [comment] 2023-10-31 03:57
Hi @samdychen , could you please share the input method you used to type Chinese characters?
Did you run into this bug when writing in the document or in a database?

**Comment by annieappflowy** [comment] 2024-04-01 12:45
Can't reproduce this issue on mac. Closing it for now.

**Closed by annieappflowy** 2024-04-01 12:45 UTC
