### ISSUE TITLE
[Bug] Cannot add events to Calendar

### ISSUE THREAD

**Issue by Xazin** [AppFlowy-IO/AppFlowy#2929] opened 2023-07-03 05:51 UTC
### Bug Description

When creating an event in the calendar, it is possible to change the type and name of the `Date` field.

Changed the type of the field to Text, and the name and value of the field respectively to `Hello` and `World`.

Then changed to another page (where the calendar is referenced), the event was now missing. Went back to the calendar view, and was then unable to add an event to the calendar at all.

### How to Reproduce

1. Create a Calendar
2. Create a Document
3. Reference the Calendar in the new document
4. Navigate to the Calendar
5. Add an event
6. Change type of the field `Date` to `Text`
7. Change name of the field `Date` to `Hello`
8. Change value of the field `Date` to `World`
9. Navigate to the Document
10. Event is missing
11. Navigate back to the Calendar
12. Try to add an event but nothing happens

### Expected Behavior

1. Create a Calendar
2. Create a Document
3. Reference the Calendar in the new document
4. Navigate to the Calendar
5. Add an event
6. The `Date` fields name and type cannot be changed

### Operating System

Windows

### AppFlowy Version(s)

0.2.5

### Additional Context

Just changing the `Date` field type to anything other than `Date` is enough to cause the bug.

**Comment by richardshiue** [comment] 2023-07-04 02:53
Hello @Xazin, I'll be working on this. I also realize the date field can be deleted as well which is definitely undesired behavior.

**Comment by annieappflowy** [comment] 2024-04-01 07:57
cannot reproduce it on macOS
closing it for now

**Closed by annieappflowy** 2024-04-01 07:57 UTC
Labels: bug, calendar, 2024
