### ISSUE TITLE
[FR] 希望可以集成 流程图 和 脑图 插件

### ISSUE THREAD

**Issue by crendy** [AppFlowy-IO/AppFlowy#439] opened 2022-04-08 07:11 UTC
希望可以集成流程图和脑图插件，
支持直接在文档进行对图的展示和编辑

**Comment by annieappflowy** [comment] 2022-04-08 07:24
Thanks @crendy for proposing a new feature. This is a duplicate of https://github.com/AppFlowy-IO/AppFlowy/issues/167
Since writing in English can benefit more members, please consider using English next time. Thanks again for your contribution!

**Closed** 2022-04-08 09:04 UTC
