### ISSUE TITLE
[Bug] high cup (about 200%) in linux 

### ISSUE THREAD

**Issue by seayuns** [AppFlowy-IO/appflowy#194] opened 2021-12-23 10:12 UTC
![image](https://user-images.githubusercontent.com/93051355/147225331-0378a806-f620-45f6-9843-e364d5415deb.png)

**Comment by MikeWallaceDev** [comment] 2021-12-23 19:15
Thank you for taking the time to send us an issue report, it's much appreciated!

Please note that we require that you fill out the template that we set up because it gives us useful information and context so that we can better fix your issue. Sometimes, not all fields are applicable, and that's ok. Just put "N/A" to let us know that you have verified that this field doesn't apply to your case.

Thanks again for helping out AppFlowy!

**Comment by appflowy** [comment] 2022-01-03 13:07
Similar to https://github.com/AppFlowy-IO/appflowy/issues/138

**Comment by MikeWallaceDev** [comment] 2022-01-06 16:22
Duplicate of #138

**Closed by MikeWallaceDev** 2022-01-06 16:22 UTC
