### ISSUE TITLE
[FR] After selecting the property type, auto enter the edit mode

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2028] opened 2023-03-20 02:50 UTC
### Description

<img width="175" alt="image" src="https://user-images.githubusercontent.com/12026239/226235222-6535dc1b-5088-4c22-b562-0ec69ea21d42.png">
<img width="144" alt="image" src="https://user-images.githubusercontent.com/12026239/226235272-919e2dd2-1ae6-408c-925a-061e07481d6e.png">

At the moment, after creating a new property type, I need to manually click to add a property name
Ideally, it should be auto entered so I don't need to click (see attached)
<img width="144" alt="image" src="https://user-images.githubusercontent.com/12026239/226235435-9135b113-1bc1-45f4-a801-d1f5785b8a62.png">

### Impact

Database users

**Comment by squidrye** [comment] 2023-03-20 03:20
Hi, I would like to work on this issue.

**Comment by Sudhanva-Nadiger** [comment] 2023-03-20 06:44
I want to work on this !

**Comment by annieappflowy** [comment] 2023-03-20 12:30
@squidrye , you are assigned to another issue, and @Sudhanva-Nadiger 's first PR was merged. Let's leave it to a first-timer. Thanks

**Comment by Sudhanva-Nadiger** [comment] 2023-03-20 12:31
Okay !

**Comment by not-shoyo** [comment] 2023-03-21 17:19
Hi, I would like to work on this issue if no one is assigned to it yet.

**Comment by annieappflowy** [comment] 2023-03-23 06:58
Thanks @not-shoyo , assigned

**Comment by richardshiue** [comment] 2023-04-11 09:17
The PR intended to fix this issue has caused a regression where the editor popover for select options in single/multi-select fields are no longer toggle-able, see the last few seconds of the following recording:



https://user-images.githubusercontent.com/71320345/231114431-85c4e46d-7b23-4239-a863-57a8c0b216b5.mp4

**Closed** 2023-04-29 08:35 UTC
Labels: help wanted, good first issue for devs, grid
