### ISSUE TITLE
[FR]  would like to add hindi translation for AppFlowy

### ISSUE THREAD

**Issue by CrazyRikin** [AppFlowy-IO/AppFlowy#3573] opened 2023-10-02 07:39 UTC
### Description

hey ,as mentioned in issue #3464 i would  like to add hindi translation in the json files.

### Impact

people who know only hindi would be benefited alot .

**Comment by MayurSMahajan** [comment] 2023-10-02 10:33
Duplicate of #2626

**Closed by MayurSMahajan** 2023-10-02 10:33 UTC
