### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by daredoole** [AppFlowy-IO/AppFlowy#5348] opened 2024-05-16 20:35 UTC
### Bug Description

If you have content within a page inside of a **Board** or a **Grid** cell it isn't viewable in the app. 

**What it looks like on PC (Is correct)**
https://github.com/AppFlowy-IO/AppFlowy/assets/49536135/f9b1c1cb-6c71-47d1-9b86-b018545f1d60

**What it looks like on IOS**
https://github.com/AppFlowy-IO/AppFlowy/assets/49536135/e5b72e27-a713-4958-8c3a-fe09572a435e

For Comparison Here's a side by side

![SideBySide](https://github.com/AppFlowy-IO/AppFlowy/assets/49536135/33844c4c-8188-4ed8-909a-f2c1d18a0c8e)

### How to Reproduce

1. On PC Create a board or a grid (since both are effected by this bug)
        a. With a board opening a cell as a page is done by clicking the arrow icon within the cell that says  "Open as Page"
        b. within a grid you just click on a specific box within the grid
3. Insert any visualization or text etc into the body of the page 
4. Check App that is linked to same account any changes to the visuals of the board or grid are seen but when cell or box as a 
5. new page nothing is there other than Properties that have been associated.

Properly adding and removing within new page window is not effected.  I did notice that there is no button in the UI for board to open as page but there is on PC.  Just something I noticed might not mean anything.

### Expected Behavior

I would expect there to be a way to see the visuals in the same way on the app as PC.

### Operating System

IOS App

### AppFlowy Version(s)

PC: 0.5.7 | IOS App 0.5.7(2)

**Comment by darrian-poole** [comment] 2024-05-16 20:36
My b forgot to put my PC specs Windows 10

**Comment by emmggi** [comment] 2024-05-17 06:59
You also forgot a title.

**Comment by Xazin** [comment] 2024-05-17 08:22
Duplicate of #5132

**Closed by Xazin** 2024-05-17 08:22 UTC

**Comment by oaklsb** [comment] 2025-03-30 11:13
Hello almost a year later I have the same problem. Is there a known solution?
