### ISSUE TITLE
[Bug] Windows 11 Input Bug

### ISSUE THREAD

**Issue by Cloud33** [AppFlowy-IO/AppFlowy#3005] opened 2023-07-14 13:30 UTC
### Bug Description

In the Windows 11 environment, using the five-stroke input method, English characters will appear after entering Chinese

Video:

https://github.com/AppFlowy-IO/AppFlowy/assets/8787198/7ac57136-7cee-4eb8-a7c1-3f33909cfaa7

### How to Reproduce

Enter the Chinese

### Expected Behavior

Displays the entered characters correctly

### Operating System

Windows11

### AppFlowy Version(s)

0.25

### Additional Context

Microsoft Five Strokes Input Method.

**Comment by teaper** [comment] 2023-07-16 04:23
The same is true for Archlinux using fcitx5 input.

**Comment by malik1988** [comment] 2023-07-21 07:37
Same happens on Windows 10

**Comment by annieappflowy** [comment] 2023-07-24 02:43
duplicate of #2020

**Closed by annieappflowy** 2023-07-24 02:43 UTC
