### ISSUE TITLE
[Bug] Link-editing pop-ups obstruct each other

### ISSUE THREAD

**Issue by Glitchy-Tozier** [AppFlowy-IO/AppFlowy#4894] opened 2024-03-13 10:15 UTC
### Bug Description

When clicking on a link, two pop-ups get triggered. One that lets you edit/format the text, and one that lets you edit the link. Both show up right above / next to the link, obstructing each other. One of the options is completely unclickable (I think it says "Remove link").

### How to Reproduce

(Bug happens on Linux, not sure about other OS)

1. Open AppFlowy
2. Click on any link on the _Getting Started_ page
3. See bug

### Expected Behavior

The pop-ups should be placed as to not overlap each other.

### Operating System

Linux Mint 21.3 Cinnamon

### AppFlowy Version(s)

0.5.1, Installed via Flatpak

### Screenshots

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/59611881/a6f4edb3-79a0-484e-825e-710c17333222)

### Additional Context

Caveat: Depending on how far you've scrolled when you click the link, the pop-ups may not overlap:

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/59611881/a33d504a-4b4d-4f17-8d56-57c115038e6d)

**Comment by Xazin** [comment] 2024-03-13 10:36
Duplicate of #4386

**Closed by Xazin** 2024-03-13 10:36 UTC
